const createDecoration = ({
  id,
  title,
  imageSrc,
  imageAlt,
  description,
  detailsDescription,
  vendorName,
  vendorLocation,
  category,
  minQuantity,
  maxQuantity,
  priceValue,
  ratingValue,
  reviewCount,
  discountLabel = '',
}) => ({
  id,
  imageSrc,
  imageAlt,
  title,
  description,
  detailsDescription,
  guestText: `Quantity: ${minQuantity} - ${maxQuantity}`,
  priceText: `${priceValue}$/pc`,
  discountLabel,
  vendorName,
  vendorLocation,
  ratingValue,
  reviewCount,
  peopleLabel: 'Quantity',
  datePlaceholder: 'Select Delivery Date',
  timePlaceholder: 'Select Delivery Time',
  actionButtonText: 'Add to Cart',
  category,
  minQuantity,
  maxQuantity,
  priceValue,
})

export const DECORATION_ITEMS = [
  createDecoration({
    id: 'balloon-arch',
    title: 'BALLOON ARCH',
    imageSrc: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Birthday balloon arch',
    description: 'Colorful balloon arch for birthdays, showers, and party entrances.',
    detailsDescription: 'A custom balloon arch with flexible color combinations, installed as an entrance or photo backdrop accent.',
    vendorName: 'Party Corner',
    vendorLocation: 'Beirut',
    category: 'Confetti & Balloons',
    minQuantity: 1,
    maxQuantity: 10,
    priceValue: 75,
    ratingValue: 4.4,
    reviewCount: 64,
  }),
  createDecoration({
    id: 'flower-bouquet',
    title: 'FLOWER BOUQUET',
    imageSrc: 'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Flowers bouquet',
    description: 'Fresh mixed bouquet with seasonal flowers and gift-ready wrapping.',
    detailsDescription: 'A bright bouquet arranged with seasonal blooms, greenery, and wrapping for gifts or table accents.',
    vendorName: 'Lancaster Plaza',
    vendorLocation: 'Beirut',
    category: 'Flowers & Greenery',
    minQuantity: 1,
    maxQuantity: 100,
    priceValue: 15,
    ratingValue: 4.5,
    reviewCount: 120,
  }),
  createDecoration({
    id: 'led-string-lights',
    title: 'LED STRING LIGHTS',
    imageSrc: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'LED decorative lights',
    description: 'Warm LED strands for mood lighting, backdrops, and table styling.',
    detailsDescription: 'Decorative LED string lights that create warm ambient scenes for indoor events and evening setups.',
    vendorName: 'Glow House',
    vendorLocation: 'Jounieh',
    category: 'Lighting',
    minQuantity: 5,
    maxQuantity: 200,
    priceValue: 5,
    ratingValue: 4.6,
    reviewCount: 92,
    discountLabel: 'Buy 9 get 2 for free',
  }),
  createDecoration({
    id: 'table-centerpiece',
    title: 'TABLE CENTERPIECE',
    imageSrc: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event table centerpiece',
    description: 'Elegant table centerpiece with flowers, candles, and greenery.',
    detailsDescription: 'A refined centerpiece arrangement built for dining tables, guest tables, and formal celebration layouts.',
    vendorName: 'Bloom Atelier',
    vendorLocation: 'Achrafieh',
    category: 'Table Decorations',
    minQuantity: 4,
    maxQuantity: 80,
    priceValue: 28,
    ratingValue: 4.7,
    reviewCount: 88,
  }),
  createDecoration({
    id: 'photo-backdrop',
    title: 'PHOTO BACKDROP',
    imageSrc: 'https://images.unsplash.com/photo-1504196606672-aef5c9cefc92?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Decorative photo backdrop',
    description: 'Decorative photo wall with fabric, greenery, and themed accents.',
    detailsDescription: 'A statement photo backdrop with layered fabric, greenery, and optional signage for guest photos.',
    vendorName: 'Scene Makers',
    vendorLocation: 'Beirut',
    category: 'Backdrops',
    minQuantity: 1,
    maxQuantity: 8,
    priceValue: 120,
    ratingValue: 4.6,
    reviewCount: 71,
    discountLabel: 'Custom colors',
  }),
  createDecoration({
    id: 'aisle-runner',
    title: 'AISLE RUNNER',
    imageSrc: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Wedding aisle runner',
    description: 'Ceremony aisle runner with petals and side accents.',
    detailsDescription: 'A ceremony aisle setup with runner fabric, flower petals, and optional lanterns or side greenery.',
    vendorName: 'White Rose Events',
    vendorLocation: 'Byblos',
    category: 'Ceremony Decor',
    minQuantity: 1,
    maxQuantity: 20,
    priceValue: 65,
    ratingValue: 4.5,
    reviewCount: 53,
  }),
  createDecoration({
    id: 'candle-set',
    title: 'CANDLE SET',
    imageSrc: 'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Decorative candle set',
    description: 'Vanilla candles in mixed heights for warm table ambiance.',
    detailsDescription: 'A set of decorative candles with holders, ideal for dinner tables, lounges, and romantic evening styling.',
    vendorName: 'Glow House',
    vendorLocation: 'Jounieh',
    category: 'Lighting',
    minQuantity: 10,
    maxQuantity: 300,
    priceValue: 2,
    ratingValue: 4.3,
    reviewCount: 66,
  }),
  createDecoration({
    id: 'confetti-cannons',
    title: 'CONFETTI CANNONS',
    imageSrc: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Confetti at party',
    description: 'Handheld confetti cannons for entrances, countdowns, and finales.',
    detailsDescription: 'Colorful confetti cannons designed for party moments, wedding entrances, stage reveals, and countdowns.',
    vendorName: 'Party Corner',
    vendorLocation: 'Beirut',
    category: 'Confetti & Balloons',
    minQuantity: 4,
    maxQuantity: 150,
    priceValue: 6,
    ratingValue: 4.2,
    reviewCount: 37,
  }),
  createDecoration({
    id: 'greenery-garland',
    title: 'GREENERY GARLAND',
    imageSrc: 'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Greenery garland',
    description: 'Fresh greenery garlands for tables, arches, staircases, and bars.',
    detailsDescription: 'Flexible greenery garlands made with fresh leaves and accents for natural event styling.',
    vendorName: 'Bloom Atelier',
    vendorLocation: 'Achrafieh',
    category: 'Flowers & Greenery',
    minQuantity: 3,
    maxQuantity: 120,
    priceValue: 18,
    ratingValue: 4.6,
    reviewCount: 82,
  }),
  createDecoration({
    id: 'welcome-sign',
    title: 'WELCOME SIGN',
    imageSrc: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event welcome sign',
    description: 'Custom welcome sign with easel, florals, and event wording.',
    detailsDescription: 'A personalized entrance sign mounted on an easel with optional floral styling and custom text.',
    vendorName: 'Ink and Bloom',
    vendorLocation: 'Dbayeh',
    category: 'Signage',
    minQuantity: 1,
    maxQuantity: 10,
    priceValue: 45,
    ratingValue: 4.4,
    reviewCount: 42,
  }),
  createDecoration({
    id: 'chair-sashes',
    title: 'CHAIR SASHES',
    imageSrc: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Decorated event chairs',
    description: 'Fabric chair sashes in multiple colors for ceremony and dining setups.',
    detailsDescription: 'Soft chair sashes available in several colors, tied and styled for guest seating or ceremony rows.',
    vendorName: 'Table Story',
    vendorLocation: 'Beirut',
    category: 'Table Decorations',
    minQuantity: 20,
    maxQuantity: 600,
    priceValue: 1.5,
    ratingValue: 4.1,
    reviewCount: 29,
  }),
  createDecoration({
    id: 'lantern-pathway',
    title: 'LANTERN PATHWAY',
    imageSrc: 'https://images.unsplash.com/photo-1482575832494-771f74bf6857?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Lantern pathway decor',
    description: 'Decorative lanterns for pathways, garden corners, and entrances.',
    detailsDescription: 'Lantern sets with warm lighting for outdoor paths, venue entrances, aisle sides, and garden corners.',
    vendorName: 'Glow House',
    vendorLocation: 'Jounieh',
    category: 'Lighting',
    minQuantity: 6,
    maxQuantity: 120,
    priceValue: 9,
    ratingValue: 4.5,
    reviewCount: 74,
  }),
  createDecoration({
    id: 'dessert-table-props',
    title: 'DESSERT TABLE PROPS',
    imageSrc: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Dessert table props',
    description: 'Cake stands, trays, risers, and labels for dessert displays.',
    detailsDescription: 'A coordinated dessert table prop set with stands, trays, risers, small labels, and decorative accents.',
    vendorName: 'Sugar Studio',
    vendorLocation: 'Dbayeh',
    category: 'Table Decorations',
    minQuantity: 1,
    maxQuantity: 25,
    priceValue: 35,
    ratingValue: 4.7,
    reviewCount: 57,
  }),
  createDecoration({
    id: 'neon-sign',
    title: 'NEON SIGN',
    imageSrc: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Neon event sign',
    description: 'Neon-style sign for photo corners, dance floors, and backdrops.',
    detailsDescription: 'A glowing neon-style sign with event-friendly phrases or custom wording for nightlife-style decor.',
    vendorName: 'Bright Letters',
    vendorLocation: 'Mar Mikhael',
    category: 'Signage',
    minQuantity: 1,
    maxQuantity: 12,
    priceValue: 90,
    ratingValue: 4.6,
    reviewCount: 61,
    discountLabel: 'Photo favorite',
  }),
  createDecoration({
    id: 'draped-ceiling',
    title: 'DRAPED CEILING',
    imageSrc: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Draped ceiling decoration',
    description: 'Soft ceiling drapes for halls, tents, and formal receptions.',
    detailsDescription: 'Fabric ceiling draping that softens indoor halls or tents and adds a formal event atmosphere.',
    vendorName: 'Scene Makers',
    vendorLocation: 'Beirut',
    category: 'Backdrops',
    minQuantity: 1,
    maxQuantity: 15,
    priceValue: 180,
    ratingValue: 4.8,
    reviewCount: 93,
    discountLabel: 'Premium',
  }),
]
