const decorationAsset = (folder, fileName) => `/assets/decorations/${folder}/${fileName}`

const decorationGallery = (folder, decorationName, fileNames) =>
  fileNames.map((fileName, index) => ({
    src: decorationAsset(folder, fileName),
    alt:
      index === 0
        ? `${decorationName} main image`
        : `${decorationName} gallery image ${index}`,
  }))

const createDecoration = ({
  id,
  title,
  imageSrc,
  imageAlt,
  galleryImages,
  description,
  detailsDescription,
  vendorName,
  vendorLocation,
  vendorLogoSrc,
  vendorLogoAlt,
  category,
  minQuantity,
  maxQuantity,
  priceValue,
  ratingValue,
  reviewCount,
  discountLabel = '',
}) => ({
  id,
  imageSrc,
  imageAlt,
  title,
  description,
  detailsDescription,
  guestText: `Quantity: ${minQuantity} - ${maxQuantity}`,
  priceText: `${priceValue}$/pc`,
  discountLabel,
  vendorName,
  vendorLocation,
  ratingValue,
  reviewCount,
  peopleLabel: 'Quantity',
  datePlaceholder: 'Select Delivery Date',
  timePlaceholder: 'Select Delivery Time',
  actionButtonText: 'Add to Cart',
  category,
  minQuantity,
  maxQuantity,
  priceValue,
  vendorLogoSrc,
  vendorLogoAlt: vendorLogoAlt || `${vendorName} logo`,
  galleryImages:
    Array.isArray(galleryImages) && galleryImages.length > 0
      ? galleryImages
      : [
          {
            src: imageSrc,
            alt: imageAlt,
          },
        ],
})

export const DECORATION_ITEMS = [
  createDecoration({
    id: 'balloon-arch',
    title: 'BALLOON ARCH',
    imageSrc: decorationAsset('balloonarch', 'main.webp'),
    imageAlt: 'Birthday balloon arch',
    galleryImages: decorationGallery('balloonarch', 'Balloon Arch', [
      'main.webp',
      '1.webp',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Colorful balloon arch for birthdays, showers, and party entrances.',
    detailsDescription: 'A custom balloon arch with flexible color combinations, installed as an entrance or photo backdrop accent.',
    vendorName: 'The Balloon Event Company',
    vendorLocation: 'Beirut',
    vendorLogoSrc: decorationAsset('balloonarch', 'logo.webp'),
    category: 'Confetti & Balloons',
    minQuantity: 1,
    maxQuantity: 10,
    priceValue: 75,
    ratingValue: 4.4,
    reviewCount: 64,
  }),
  createDecoration({
    id: 'flower-bouquet',
    title: 'FLOWER BOUQUET',
    imageSrc: decorationAsset('flowerbouquet', 'main.webp'),
    imageAlt: 'Flowers bouquet',
    galleryImages: decorationGallery('flowerbouquet', 'Flower Bouquet', [
      'main.webp',
      '1.webp',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Fresh mixed bouquet with seasonal flowers and gift-ready wrapping.',
    detailsDescription: 'A bright bouquet arranged with seasonal blooms, greenery, and wrapping for gifts or table accents.',
    vendorName: 'LEFLEOUR',
    vendorLocation: 'Beirut',
    vendorLogoSrc: decorationAsset('flowerbouquet', 'logo.webp'),
    category: 'Flowers & Greenery',
    minQuantity: 1,
    maxQuantity: 100,
    priceValue: 15,
    ratingValue: 4.5,
    reviewCount: 120,
  }),
  createDecoration({
    id: 'led-string-lights',
    title: 'LED STRING LIGHTS',
    imageSrc: decorationAsset('ledstringlights', 'main.jpg'),
    imageAlt: 'LED decorative lights',
    galleryImages: decorationGallery('ledstringlights', 'LED String Lights', [
      'main.jpg',
      '1.webp',
      '2.webp',
      '3.webp',
    ]),
    description: 'Warm LED strands for mood lighting, backdrops, and table styling.',
    detailsDescription: 'Decorative LED string lights that create warm ambient scenes for indoor events and evening setups.',
    vendorName: 'The Led Store',
    vendorLocation: 'Jounieh',
    vendorLogoSrc: decorationAsset('ledstringlights', 'logo.png'),
    category: 'Lighting',
    minQuantity: 5,
    maxQuantity: 200,
    priceValue: 5,
    ratingValue: 4.6,
    reviewCount: 92,
    discountLabel: 'Buy 9 get 2 for free',
  }),
  createDecoration({
    id: 'table-centerpiece',
    title: 'TABLE CENTERPIECE',
    imageSrc: decorationAsset('tablecenterpiece', 'main.avif'),
    imageAlt: 'Event table centerpiece',
    galleryImages: decorationGallery('tablecenterpiece', 'Table Centerpiece', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Elegant table centerpiece with flowers, candles, and greenery.',
    detailsDescription: 'A refined centerpiece arrangement built for dining tables, guest tables, and formal celebration layouts.',
    vendorName: 'WILLOW & HIVE',
    vendorLocation: 'Achrafieh',
    vendorLogoSrc: decorationAsset('tablecenterpiece', 'logo.jpg'),
    category: 'Table Decorations',
    minQuantity: 4,
    maxQuantity: 80,
    priceValue: 28,
    ratingValue: 4.7,
    reviewCount: 88,
  }),
  createDecoration({
    id: 'photo-backdrop',
    title: 'PHOTO BACKDROP',
    imageSrc: decorationAsset('photobackdrop', 'main.jpg'),
    imageAlt: 'Decorative photo backdrop',
    galleryImages: decorationGallery('photobackdrop', 'Photo Backdrop', [
      'main.jpg',
      '1.jpg',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Decorative photo wall with fabric, greenery, and themed accents.',
    detailsDescription: 'A statement photo backdrop with layered fabric, greenery, and optional signage for guest photos.',
    vendorName: 'WILLOW & HIVE',
    vendorLocation: 'Beirut',
    vendorLogoSrc: decorationAsset('photobackdrop', 'logo.jpg'),
    category: 'Backdrops',
    minQuantity: 1,
    maxQuantity: 8,
    priceValue: 120,
    ratingValue: 4.6,
    reviewCount: 71,
    discountLabel: 'Custom colors',
  }),
  createDecoration({
    id: 'aisle-runner',
    title: 'AISLE RUNNER',
    imageSrc: decorationAsset('aislerunner', 'main.avif'),
    imageAlt: 'Wedding aisle runner',
    galleryImages: decorationGallery('aislerunner', 'Aisle Runner', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Ceremony aisle runner with petals and side accents.',
    detailsDescription: 'A ceremony aisle setup with runner fabric, flower petals, and optional lanterns or side greenery.',
    vendorName: 'The Wedding Shop',
    vendorLocation: 'Byblos',
    vendorLogoSrc: decorationAsset('aislerunner', 'logo.png'),
    category: 'Ceremony Decor',
    minQuantity: 1,
    maxQuantity: 20,
    priceValue: 65,
    ratingValue: 4.5,
    reviewCount: 53,
  }),
  createDecoration({
    id: 'candle-set',
    title: 'CANDLE SET',
    imageSrc: decorationAsset('candleset', 'main.avif'),
    imageAlt: 'Decorative candle set',
    galleryImages: decorationGallery('candleset', 'Candle Set', [
      'main.avif',
      '1.webp',
      '2.jpg',
      '3.webp',
    ]),
    description: 'Vanilla candles in mixed heights for warm table ambiance.',
    detailsDescription: 'A set of decorative candles with holders, ideal for dinner tables, lounges, and romantic evening styling.',
    vendorName: 'The Wedding Shop',
    vendorLocation: 'Jounieh',
    vendorLogoSrc: decorationAsset('candleset', 'logo.png'),
    category: 'Lighting',
    minQuantity: 10,
    maxQuantity: 300,
    priceValue: 2,
    ratingValue: 4.3,
    reviewCount: 66,
  }),
  createDecoration({
    id: 'confetti-cannons',
    title: 'CONFETTI CANNONS',
    imageSrc: decorationAsset('confetticannons', 'main.avif'),
    imageAlt: 'Confetti at party',
    galleryImages: decorationGallery('confetticannons', 'Confetti Cannons', [
      'main.avif',
      '1.jpg',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Handheld confetti cannons for entrances, countdowns, and finales.',
    detailsDescription: 'Colorful confetti cannons designed for party moments, wedding entrances, stage reveals, and countdowns.',
    vendorName: 'Confetti Zone',
    vendorLocation: 'Beirut',
    vendorLogoSrc: decorationAsset('confetticannons', 'logo.png'),
    category: 'Confetti & Balloons',
    minQuantity: 4,
    maxQuantity: 150,
    priceValue: 6,
    ratingValue: 4.2,
    reviewCount: 37,
  }),
  createDecoration({
    id: 'greenery-garland',
    title: 'GREENERY GARLAND',
    imageSrc: decorationAsset('greenarygarland', 'main.webp'),
    imageAlt: 'Greenery garland',
    galleryImages: decorationGallery('greenarygarland', 'Greenery Garland', [
      'main.webp',
      '1.jpg',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Fresh greenery garlands for tables, arches, staircases, and bars.',
    detailsDescription: 'Flexible greenery garlands made with fresh leaves and accents for natural event styling.',
    vendorName: 'LEFLEOUR',
    vendorLocation: 'Achrafieh',
    vendorLogoSrc: decorationAsset('greenarygarland', 'logo.webp'),
    category: 'Flowers & Greenery',
    minQuantity: 3,
    maxQuantity: 120,
    priceValue: 18,
    ratingValue: 4.6,
    reviewCount: 82,
  }),
  createDecoration({
    id: 'welcome-sign',
    title: 'WELCOME SIGN',
    imageSrc: decorationAsset('welcomesign', 'main.avif'),
    imageAlt: 'Event welcome sign',
    galleryImages: decorationGallery('welcomesign', 'Welcome Sign', [
      'main.avif',
      '1.webp',
      '2.avif',
      '3.jpg',
    ]),
    description: 'Custom welcome sign with easel, florals, and event wording.',
    detailsDescription: 'A personalized entrance sign mounted on an easel with optional floral styling and custom text.',
    vendorName: 'The Wedding Shop',
    vendorLocation: 'Dbayeh',
    vendorLogoSrc: decorationAsset('welcomesign', 'logo.png'),
    category: 'Signage',
    minQuantity: 1,
    maxQuantity: 10,
    priceValue: 45,
    ratingValue: 4.4,
    reviewCount: 42,
  }),
  createDecoration({
    id: 'chair-sashes',
    title: 'CHAIR SASHES',
    imageSrc: decorationAsset('chairsashes', 'main.jpg'),
    imageAlt: 'Decorated event chairs',
    galleryImages: decorationGallery('chairsashes', 'Chair Sashes', [
      'main.jpg',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Fabric chair sashes in multiple colors for ceremony and dining setups.',
    detailsDescription: 'Soft chair sashes available in several colors, tied and styled for guest seating or ceremony rows.',
    vendorName: 'The Wedding Shop',
    vendorLocation: 'Beirut',
    vendorLogoSrc: decorationAsset('chairsashes', 'logo.png'),
    category: 'Table Decorations',
    minQuantity: 20,
    maxQuantity: 600,
    priceValue: 1.5,
    ratingValue: 4.1,
    reviewCount: 29,
  }),
  createDecoration({
    id: 'lantern-pathway',
    title: 'LANTERN PATHWAY',
    imageSrc: decorationAsset('lanternpathway', 'main.webp'),
    imageAlt: 'Lantern pathway decor',
    galleryImages: decorationGallery('lanternpathway', 'Lantern Pathway', [
      'main.webp',
      '1.jpg',
      '2.jpg',
      '3.webp',
    ]),
    description: 'Decorative lanterns for pathways, garden corners, and entrances.',
    detailsDescription: 'Lantern sets with warm lighting for outdoor paths, venue entrances, aisle sides, and garden corners.',
    vendorName: 'The Wedding Shop',
    vendorLocation: 'Jounieh',
    vendorLogoSrc: decorationAsset('lanternpathway', 'logo.png'),
    category: 'Lighting',
    minQuantity: 6,
    maxQuantity: 120,
    priceValue: 9,
    ratingValue: 4.5,
    reviewCount: 74,
  }),
  createDecoration({
    id: 'dessert-table-props',
    title: 'DESSERT TABLE PROPS',
    imageSrc: decorationAsset('desserttableprops', 'main.jpg'),
    imageAlt: 'Dessert table props',
    galleryImages: decorationGallery('desserttableprops', 'Dessert Table Props', [
      'main.jpg',
      '1.jpg',
      '2.jpg',
      '3.avif',
    ]),
    description: 'Cake stands, trays, risers, and labels for dessert displays.',
    detailsDescription: 'A coordinated dessert table prop set with stands, trays, risers, small labels, and decorative accents.',
    vendorName: 'Sugar Studio',
    vendorLocation: 'Dbayeh',
    vendorLogoSrc: decorationAsset('desserttableprops', 'logo.png'),
    category: 'Table Decorations',
    minQuantity: 1,
    maxQuantity: 25,
    priceValue: 35,
    ratingValue: 4.7,
    reviewCount: 57,
  }),
  createDecoration({
    id: 'neon-sign',
    title: 'NEON SIGN',
    imageSrc: decorationAsset('neonsign', 'main.avif'),
    imageAlt: 'Neon event sign',
    galleryImages: decorationGallery('neonsign', 'Neon Sign', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.avif',
    ]),
    description: 'Neon-style sign for photo corners, dance floors, and backdrops.',
    detailsDescription: 'A glowing neon-style sign with event-friendly phrases or custom wording for nightlife-style decor.',
    vendorName: 'The Led Store',
    vendorLocation: 'Mar Mikhael',
    vendorLogoSrc: decorationAsset('neonsign', 'logo.png'),
    category: 'Signage',
    minQuantity: 1,
    maxQuantity: 12,
    priceValue: 90,
    ratingValue: 4.6,
    reviewCount: 61,
    discountLabel: 'Photo favorite',
  }),
  createDecoration({
    id: 'draped-ceiling',
    title: 'DRAPED CEILING',
    imageSrc: decorationAsset('drapedceiling', 'main.webp'),
    imageAlt: 'Draped ceiling decoration',
    galleryImages: decorationGallery('drapedceiling', 'Draped Ceiling', [
      'main.webp',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Soft ceiling drapes for halls, tents, and formal receptions.',
    detailsDescription: 'Fabric ceiling draping that softens indoor halls or tents and adds a formal event atmosphere.',
    vendorName: 'The Wedding Shop',
    vendorLocation: 'Beirut',
    vendorLogoSrc: decorationAsset('drapedceiling', 'logo.png'),
    category: 'Backdrops',
    minQuantity: 1,
    maxQuantity: 15,
    priceValue: 180,
    ratingValue: 4.8,
    reviewCount: 93,
    discountLabel: 'Premium',
  }),
]
