export const DECORATION_ITEMS = [
  {
    id: 'balloons-1',
    imageSrc:
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Birthday balloons decoration',
    title: 'BALLOONS',
    description: 'Colorful balloon arrangements for birthdays, parties, and cheerful event styling.',
    detailsDescription:
      'Playful balloon sets designed to brighten birthdays, showers, and celebration corners with flexible color combinations and lightweight setup.',
    guestText: 'Quantity: 1 - 50',
    priceText: '0.1$/pc',
    vendorName: 'Party Corner',
    vendorLocation: 'Beirut',
    ratingValue: 4.4,
    reviewCount: 64,
    peopleLabel: 'Quantity',
    datePlaceholder: 'Select Delivery Date',
    timePlaceholder: 'Select Delivery Time',
    actionButtonText: 'Add to Cart',
    category: 'Confetti & Balloons',
    minQuantity: 1,
    maxQuantity: 50,
    priceValue: 0.1,
  },
  {
    id: 'flowers-bouquet-1',
    imageSrc:
      'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Flowers bouquet',
    title: 'FLOWER BOUQUET',
    description:
      'This bouquet contains peach roses, yellow roses, orange dahlias and snapdragons.',
    detailsDescription:
      'This bouquet contains peach roses, yellow roses, orange dahlias and snapdragons. It is arranged as a bright, gift-ready floral piece suited for celebrations and elegant event accents.',
    guestText: 'Quantity: 1 - 100',
    priceText: '15$/pc',
    vendorName: 'Lancaster Plaza',
    vendorLocation: 'Beirut',
    ratingValue: 4.5,
    reviewCount: 120,
    peopleLabel: 'Quantity',
    datePlaceholder: 'Select Delivery Date',
    timePlaceholder: 'Select Delivery Time',
    actionButtonText: 'Add to Cart',
    category: 'Flowers & Greenery',
    minQuantity: 1,
    maxQuantity: 100,
    priceValue: 15,
  },
  {
    id: 'led-lights-1',
    imageSrc:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'LED decorative lights',
    title: 'LED LIGHTS',
    description: 'Decorative LED strands for mood lighting, photo corners, and indoor event ambiance.',
    detailsDescription:
      'Decorative LED lights that help shape warm ambient scenes for indoor events, backdrops, tablescapes, and themed celebration setups.',
    guestText: 'Quantity: 5 - 200',
    priceText: '5$/pc',
    discountLabel: 'Buy 9 get 2 for free',
    vendorName: 'Glow House',
    vendorLocation: 'Jounieh',
    ratingValue: 4.6,
    reviewCount: 92,
    peopleLabel: 'Quantity',
    datePlaceholder: 'Select Delivery Date',
    timePlaceholder: 'Select Delivery Time',
    actionButtonText: 'Add to Cart',
    category: 'Lighting',
    minQuantity: 5,
    maxQuantity: 200,
    priceValue: 5,
  },
  {
    id: 'balloons-2',
    imageSrc:
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Birthday balloons decoration',
    title: 'BALLOONS',
    description: 'Colorful balloon arrangements for birthdays, parties, and cheerful event styling.',
    detailsDescription:
      'Playful balloon sets designed to brighten birthdays, showers, and celebration corners with flexible color combinations and lightweight setup.',
    guestText: 'Quantity: 1 - 50',
    priceText: '0.1$/pc',
    vendorName: 'Party Corner',
    vendorLocation: 'Beirut',
    ratingValue: 4.4,
    reviewCount: 64,
    peopleLabel: 'Quantity',
    datePlaceholder: 'Select Delivery Date',
    timePlaceholder: 'Select Delivery Time',
    actionButtonText: 'Add to Cart',
    category: 'Confetti & Balloons',
    minQuantity: 1,
    maxQuantity: 50,
    priceValue: 0.1,
  },
  {
    id: 'flowers-bouquet-2',
    imageSrc:
      'https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Flowers bouquet',
    title: 'FLOWER BOUQUET',
    description:
      'This bouquet contains peach roses, yellow roses, orange dahlias and snapdragons.',
    detailsDescription:
      'This bouquet contains peach roses, yellow roses, orange dahlias and snapdragons. It is arranged as a bright, gift-ready floral piece suited for celebrations and elegant event accents.',
    guestText: 'Quantity: 1 - 100',
    priceText: '15$/pc',
    vendorName: 'Lancaster Plaza',
    vendorLocation: 'Beirut',
    ratingValue: 4.5,
    reviewCount: 120,
    peopleLabel: 'Quantity',
    datePlaceholder: 'Select Delivery Date',
    timePlaceholder: 'Select Delivery Time',
    actionButtonText: 'Add to Cart',
    category: 'Flowers & Greenery',
    minQuantity: 1,
    maxQuantity: 100,
    priceValue: 15,
  },
  {
    id: 'led-lights-2',
    imageSrc:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'LED decorative lights',
    title: 'LED LIGHTS',
    description: 'Decorative LED strands for mood lighting, photo corners, and indoor event ambiance.',
    detailsDescription:
      'Decorative LED lights that help shape warm ambient scenes for indoor events, backdrops, tablescapes, and themed celebration setups.',
    guestText: 'Quantity: 5 - 200',
    priceText: '5$/pc',
    discountLabel: 'Buy 9 get 2 for free',
    vendorName: 'Glow House',
    vendorLocation: 'Jounieh',
    ratingValue: 4.6,
    reviewCount: 92,
    peopleLabel: 'Quantity',
    datePlaceholder: 'Select Delivery Date',
    timePlaceholder: 'Select Delivery Time',
    actionButtonText: 'Add to Cart',
    category: 'Lighting',
    minQuantity: 5,
    maxQuantity: 200,
    priceValue: 5,
  },
]
