const entertainmentLogo = (text, bg = '111111', color = 'ffffff') =>
  `https://dummyimage.com/120x54/${bg}/${color}.png&text=${encodeURIComponent(text)}`

const createEntertainment = ({
  id,
  title,
  imageSrc,
  imageAlt,
  description,
  detailsDescription,
  priceText,
  vendorName,
  vendorLocation,
  detailBadgeText,
  category,
  location,
  priceValue,
  ratingValue,
  reviewCount,
  discountLabel = '',
  logoText,
}) => ({
  id,
  imageSrc,
  imageAlt,
  title,
  description,
  detailsDescription,
  guestText: '',
  priceText,
  discountLabel,
  vendorName,
  vendorLocation,
  ratingValue,
  reviewCount,
  detailBadgeText,
  showPeopleSelector: false,
  datePlaceholder: 'Select Performance Date',
  timePlaceholder: 'Select Performance Time',
  actionButtonText: 'Add to Cart',
  category,
  location,
  priceValue,
  vendorLogoSrc: entertainmentLogo(logoText || vendorName),
  vendorLogoAlt: `${vendorName} logo`,
})

export const ENTERTAINMENT_ITEMS = [
  createEntertainment({
    id: 'face-painting',
    title: 'FACE PAINTING',
    imageSrc: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Face painting for kids',
    description: 'Colorful face painting activity for kids of all ages.',
    detailsDescription: 'A playful face painting experience with colorful designs for birthdays, school events, and family-friendly celebrations.',
    priceText: '30$/Day',
    vendorName: 'Fun Factory',
    vendorLocation: 'Beirut',
    detailBadgeText: 'Kids Activity',
    category: 'Animation',
    location: 'Beirut',
    priceValue: 30,
    ratingValue: 4.4,
    reviewCount: 76,
  }),
  createEntertainment({
    id: 'dj-rodge',
    title: 'DJ RODGE',
    imageSrc: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'DJ performing at an event',
    description: 'High-energy house music set for weddings, parties, and nightlife events.',
    detailsDescription: 'A vibrant DJ set with polished transitions, dance-floor momentum, and flexible playlists for private events.',
    priceText: '500$/Day',
    vendorName: 'DJ Rodge',
    vendorLocation: 'Jounieh',
    detailBadgeText: 'House Music',
    category: 'Music',
    location: 'Jounieh',
    priceValue: 500,
    ratingValue: 4.5,
    reviewCount: 120,
    logoText: 'RODGE',
  }),
  createEntertainment({
    id: 'traditional-zaffe',
    title: 'ZAFFE',
    imageSrc: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Traditional zaffe performers',
    description: 'Traditional live entrance performance with dabke, drums, and festive energy.',
    detailsDescription: 'A traditional zaffe performance with dancers, percussion, and celebratory movement for weddings and major events.',
    priceText: '100$/Night',
    vendorName: 'Crystal Events',
    vendorLocation: 'Byblos',
    detailBadgeText: 'Live Performance',
    category: 'Dancing',
    location: 'Byblos',
    priceValue: 100,
    ratingValue: 4.6,
    reviewCount: 88,
  }),
  createEntertainment({
    id: 'live-jazz-band',
    title: 'LIVE JAZZ BAND',
    imageSrc: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Live jazz band',
    description: 'Smooth jazz trio for dinners, cocktail hours, and formal receptions.',
    detailsDescription: 'A live jazz trio with saxophone, keys, and percussion for elegant dinner and cocktail atmospheres.',
    priceText: '650$/Night',
    vendorName: 'Blue Note Trio',
    vendorLocation: 'Beirut',
    detailBadgeText: 'Live Music',
    category: 'Music',
    location: 'Beirut',
    priceValue: 650,
    ratingValue: 4.8,
    reviewCount: 97,
    discountLabel: 'Elegant choice',
  }),
  createEntertainment({
    id: 'kids-magician',
    title: 'KIDS MAGICIAN',
    imageSrc: 'https://images.unsplash.com/photo-1505455184862-554165e5f6ba?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Magician performing for kids',
    description: 'Interactive magic show with comedy, tricks, and child-friendly audience moments.',
    detailsDescription: 'A cheerful magician performance designed for birthdays, school events, and family celebrations.',
    priceText: '180$/Show',
    vendorName: 'Magic Mira',
    vendorLocation: 'Tripoli',
    detailBadgeText: 'Magic Show',
    category: 'Animation',
    location: 'Tripoli',
    priceValue: 180,
    ratingValue: 4.5,
    reviewCount: 64,
  }),
  createEntertainment({
    id: 'fireworks-show',
    title: 'FIREWORKS SHOW',
    imageSrc: 'https://images.unsplash.com/photo-1533236897111-3e94666b2edf?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Fireworks show',
    description: 'Outdoor fireworks finale for weddings, festivals, and milestone events.',
    detailsDescription: 'A coordinated fireworks show with timed sequences and event-safe planning for outdoor celebrations.',
    priceText: '1200$/Show',
    vendorName: 'Sky Burst',
    vendorLocation: 'Zahle',
    detailBadgeText: 'Outdoor Show',
    category: 'Special Effects',
    location: 'Zahle',
    priceValue: 1200,
    ratingValue: 4.7,
    reviewCount: 51,
    discountLabel: 'Finale show',
  }),
  createEntertainment({
    id: 'photo-booth',
    title: 'PHOTO BOOTH',
    imageSrc: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Photo booth camera setup',
    description: 'Photo booth with props, instant prints, and digital sharing.',
    detailsDescription: 'A staffed photo booth experience with props, printed keepsakes, digital gallery, and event branding options.',
    priceText: '250$/Day',
    vendorName: 'Snap Station',
    vendorLocation: 'Dbayeh',
    detailBadgeText: 'Photo Booth',
    category: 'Interactive',
    location: 'Dbayeh',
    priceValue: 250,
    ratingValue: 4.4,
    reviewCount: 83,
  }),
  createEntertainment({
    id: 'dabke-group',
    title: 'DABKE GROUP',
    imageSrc: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Dabke dance group',
    description: 'Traditional dabke dancers for weddings, cultural events, and entrances.',
    detailsDescription: 'A lively dabke group with coordinated choreography, traditional energy, and audience engagement.',
    priceText: '350$/Show',
    vendorName: 'Levant Steps',
    vendorLocation: 'Saida',
    detailBadgeText: 'Traditional Dance',
    category: 'Dancing',
    location: 'Saida',
    priceValue: 350,
    ratingValue: 4.6,
    reviewCount: 69,
  }),
  createEntertainment({
    id: 'acoustic-duo',
    title: 'ACOUSTIC DUO',
    imageSrc: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Acoustic musicians',
    description: 'Acoustic guitar and vocal duo for ceremonies, dinners, and cocktail hours.',
    detailsDescription: 'A warm acoustic duo with customizable setlists for wedding ceremonies, receptions, and intimate dinners.',
    priceText: '320$/Night',
    vendorName: 'Soft Strings',
    vendorLocation: 'Byblos',
    detailBadgeText: 'Acoustic Music',
    category: 'Music',
    location: 'Byblos',
    priceValue: 320,
    ratingValue: 4.7,
    reviewCount: 58,
  }),
  createEntertainment({
    id: 'circus-performers',
    title: 'CIRCUS PERFORMERS',
    imageSrc: 'https://images.unsplash.com/photo-1509824227185-9c5a01ceba0d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Circus performers',
    description: 'Stilt walkers, jugglers, and roaming circus acts for lively events.',
    detailsDescription: 'A roaming circus entertainment package with visual performers, juggling, stilt walking, and guest interaction.',
    priceText: '420$/Day',
    vendorName: 'Carnival Crew',
    vendorLocation: 'Beirut',
    detailBadgeText: 'Roaming Acts',
    category: 'Animation',
    location: 'Beirut',
    priceValue: 420,
    ratingValue: 4.5,
    reviewCount: 44,
  }),
  createEntertainment({
    id: 'karaoke-host',
    title: 'KARAOKE HOST',
    imageSrc: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Karaoke microphone',
    description: 'Hosted karaoke night with microphones, screen, and song library.',
    detailsDescription: 'A complete karaoke setup with a host, sound system, lyrics screen, microphones, and a wide song catalog.',
    priceText: '220$/Night',
    vendorName: 'Sing Along LB',
    vendorLocation: 'Hamra',
    detailBadgeText: 'Karaoke',
    category: 'Interactive',
    location: 'Hamra',
    priceValue: 220,
    ratingValue: 4.2,
    reviewCount: 39,
  }),
  createEntertainment({
    id: 'led-dance-show',
    title: 'LED DANCE SHOW',
    imageSrc: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'LED dance performance',
    description: 'High-impact LED dance performance for entrances and stage moments.',
    detailsDescription: 'A choreographed LED dance act with glowing costumes, upbeat music, and a visual stage presence.',
    priceText: '550$/Show',
    vendorName: 'Neon Motion',
    vendorLocation: 'Mar Mikhael',
    detailBadgeText: 'Stage Show',
    category: 'Dancing',
    location: 'Mar Mikhael',
    priceValue: 550,
    ratingValue: 4.6,
    reviewCount: 47,
    discountLabel: 'Visual act',
  }),
  createEntertainment({
    id: 'puppet-show',
    title: 'PUPPET SHOW',
    imageSrc: 'https://images.unsplash.com/photo-1604881991720-f91add269bed?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Puppet show for kids',
    description: 'Story-driven puppet show for birthdays and school events.',
    detailsDescription: 'A child-friendly puppet show with stories, music, audience interaction, and a compact stage setup.',
    priceText: '150$/Show',
    vendorName: 'Story Box',
    vendorLocation: 'Jounieh',
    detailBadgeText: 'Kids Show',
    category: 'Animation',
    location: 'Jounieh',
    priceValue: 150,
    ratingValue: 4.3,
    reviewCount: 35,
  }),
  createEntertainment({
    id: 'saxophonist',
    title: 'SAXOPHONIST',
    imageSrc: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Saxophonist performing',
    description: 'Solo saxophonist for cocktail hours, lounges, and wedding entrances.',
    detailsDescription: 'A solo saxophone performance with smooth, upbeat, or romantic sets tailored to the event mood.',
    priceText: '280$/Night',
    vendorName: 'Sax by Sam',
    vendorLocation: 'Achrafieh',
    detailBadgeText: 'Solo Musician',
    category: 'Music',
    location: 'Achrafieh',
    priceValue: 280,
    ratingValue: 4.8,
    reviewCount: 73,
  }),
  createEntertainment({
    id: 'laser-show',
    title: 'LASER SHOW',
    imageSrc: 'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Laser light show',
    description: 'Laser light show synchronized with music for stages and dance floors.',
    detailsDescription: 'A programmed laser show with music synchronization, stage-safe setup, and high-impact lighting effects.',
    priceText: '850$/Show',
    vendorName: 'Beam Lab',
    vendorLocation: 'Beirut',
    detailBadgeText: 'Light Show',
    category: 'Special Effects',
    location: 'Beirut',
    priceValue: 850,
    ratingValue: 4.6,
    reviewCount: 52,
    discountLabel: 'Premium',
  }),
]
