const entertainmentLogo = (text, bg = '111111', color = 'ffffff') =>
  `https://dummyimage.com/120x54/${bg}/${color}.png&text=${encodeURIComponent(text)}`

const entertainmentAsset = (folder, fileName) => `/assets/entertainment/${folder}/${fileName}`

const entertainmentGallery = (folder, entertainmentName, fileNames) =>
  fileNames.map((fileName, index) => ({
    src: entertainmentAsset(folder, fileName),
    alt:
      index === 0
        ? `${entertainmentName} main image`
        : `${entertainmentName} gallery image ${index}`,
  }))

const createEntertainment = ({
  id,
  title,
  imageSrc,
  imageAlt,
  galleryImages,
  description,
  detailsDescription,
  priceText,
  vendorName,
  vendorLocation,
  vendorLogoSrc,
  vendorLogoAlt,
  detailBadgeText,
  category,
  location,
  priceValue,
  ratingValue,
  reviewCount,
  discountLabel = '',
  logoText,
}) => ({
  id,
  imageSrc,
  imageAlt,
  title,
  description,
  detailsDescription,
  guestText: '',
  priceText,
  discountLabel,
  vendorName,
  vendorLocation,
  ratingValue,
  reviewCount,
  detailBadgeText,
  showPeopleSelector: false,
  datePlaceholder: 'Select Performance Date',
  timePlaceholder: 'Select Performance Time',
  actionButtonText: 'Add to Cart',
  category,
  location,
  priceValue,
  vendorLogoSrc: vendorLogoSrc || entertainmentLogo(logoText || vendorName),
  vendorLogoAlt: vendorLogoAlt || `${vendorName} logo`,
  galleryImages:
    Array.isArray(galleryImages) && galleryImages.length > 0
      ? galleryImages
      : [
          {
            src: imageSrc,
            alt: imageAlt,
          },
        ],
})

export const ENTERTAINMENT_ITEMS = [
  createEntertainment({
    id: 'face-painting',
    title: 'FACE PAINTING',
    imageSrc: entertainmentAsset('facepainting', 'main.avif'),
    imageAlt: 'Face painting for kids',
    galleryImages: entertainmentGallery('facepainting', 'Face Painting', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.webp',
    ]),
    description: 'Colorful face painting activity for kids of all ages.',
    detailsDescription: 'A playful face painting experience with colorful designs for birthdays, school events, and family-friendly celebrations.',
    priceText: '30$/Day',
    vendorName: 'Fun Factory',
    vendorLocation: 'Beirut',
    vendorLogoSrc: entertainmentAsset('facepainting', 'logo.png'),
    detailBadgeText: 'Kids Activity',
    category: 'Animation',
    location: 'Beirut',
    priceValue: 30,
    ratingValue: 4.4,
    reviewCount: 76,
  }),
  createEntertainment({
    id: 'dj-rodge',
    title: 'DJ RODGE',
    imageSrc: entertainmentAsset('djrodge', 'main.avif'),
    imageAlt: 'DJ performing at an event',
    galleryImages: entertainmentGallery('djrodge', 'DJ Rodge', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'High-energy house music set for weddings, parties, and nightlife events.',
    detailsDescription: 'A vibrant DJ set with polished transitions, dance-floor momentum, and flexible playlists for private events.',
    priceText: '500$/Day',
    vendorName: 'DJ Rodge',
    vendorLocation: 'Jounieh',
    vendorLogoSrc: entertainmentAsset('djrodge', 'logo.png'),
    detailBadgeText: 'House Music',
    category: 'Music',
    location: 'Jounieh',
    priceValue: 500,
    ratingValue: 4.5,
    reviewCount: 120,
    logoText: 'RODGE',
  }),
  createEntertainment({
    id: 'traditional-zaffe',
    title: 'ZAFFE',
    imageSrc: entertainmentAsset('zaffe', 'main.jpg'),
    imageAlt: 'Traditional zaffe performers',
    galleryImages: entertainmentGallery('zaffe', 'Zaffe', [
      'main.jpg',
      '1.jpeg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Traditional live entrance performance with dabke, drums, and festive energy.',
    detailsDescription: 'A traditional zaffe performance with dancers, percussion, and celebratory movement for weddings and major events.',
    priceText: '100$/Night',
    vendorName: 'Crystal Events',
    vendorLocation: 'Byblos',
    vendorLogoSrc: entertainmentAsset('zaffe', 'logo.png'),
    detailBadgeText: 'Live Performance',
    category: 'Dancing',
    location: 'Byblos',
    priceValue: 100,
    ratingValue: 4.6,
    reviewCount: 88,
  }),
  createEntertainment({
    id: 'live-jazz-band',
    title: 'LIVE JAZZ BAND',
    imageSrc: entertainmentAsset('livejazzband', 'main.avif'),
    imageAlt: 'Live jazz band',
    galleryImages: entertainmentGallery('livejazzband', 'Live Jazz Band', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Smooth jazz trio for dinners, cocktail hours, and formal receptions.',
    detailsDescription: 'A live jazz trio with saxophone, keys, and percussion for elegant dinner and cocktail atmospheres.',
    priceText: '650$/Night',
    vendorName: 'Blue Note Trio',
    vendorLocation: 'Beirut',
    vendorLogoSrc: entertainmentAsset('livejazzband', 'logo.jpg'),
    detailBadgeText: 'Live Music',
    category: 'Music',
    location: 'Beirut',
    priceValue: 650,
    ratingValue: 4.8,
    reviewCount: 97,
    discountLabel: 'Elegant choice',
  }),
  createEntertainment({
    id: 'kids-magician',
    title: 'KIDS MAGICIAN',
    imageSrc: entertainmentAsset('kidsmagician', 'main.jpg'),
    imageAlt: 'Magician performing for kids',
    galleryImages: entertainmentGallery('kidsmagician', 'Kids Magician', [
      'main.jpg',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Interactive magic show with comedy, tricks, and child-friendly audience moments.',
    detailsDescription: 'A cheerful magician performance designed for birthdays, school events, and family celebrations.',
    priceText: '180$/Show',
    vendorName: 'Magic Mira',
    vendorLocation: 'Tripoli',
    vendorLogoSrc: entertainmentAsset('kidsmagician', 'logo.png'),
    detailBadgeText: 'Magic Show',
    category: 'Animation',
    location: 'Tripoli',
    priceValue: 180,
    ratingValue: 4.5,
    reviewCount: 64,
  }),
  createEntertainment({
    id: 'fireworks-show',
    title: 'FIREWORKS SHOW',
    imageSrc: entertainmentAsset('fireworksshow', 'main.jpeg'),
    imageAlt: 'Fireworks show',
    galleryImages: entertainmentGallery('fireworksshow', 'Fireworks Show', [
      'main.jpeg',
      '1.webp',
      '2.jpg',
      '3.png',
    ]),
    description: 'Outdoor fireworks finale for weddings, festivals, and milestone events.',
    detailsDescription: 'A coordinated fireworks show with timed sequences and event-safe planning for outdoor celebrations.',
    priceText: '1200$/Show',
    vendorName: 'Sky Burst',
    vendorLocation: 'Zahle',
    vendorLogoSrc: entertainmentAsset('fireworksshow', 'logo.png'),
    detailBadgeText: 'Outdoor Show',
    category: 'Special Effects',
    location: 'Zahle',
    priceValue: 1200,
    ratingValue: 4.7,
    reviewCount: 51,
    discountLabel: 'Finale show',
  }),
  createEntertainment({
    id: 'photo-booth',
    title: 'PHOTO BOOTH',
    imageSrc: entertainmentAsset('photobooth', 'main.avif'),
    imageAlt: 'Photo booth camera setup',
    galleryImages: entertainmentGallery('photobooth', 'Photo Booth', [
      'main.avif',
      '1.jpg',
      '2.avif',
      '3.png',
    ]),
    description: 'Photo booth with props, instant prints, and digital sharing.',
    detailsDescription: 'A staffed photo booth experience with props, printed keepsakes, digital gallery, and event branding options.',
    priceText: '250$/Day',
    vendorName: 'Snap Station',
    vendorLocation: 'Dbayeh',
    vendorLogoSrc: entertainmentAsset('photobooth', 'logo.png'),
    detailBadgeText: 'Photo Booth',
    category: 'Interactive',
    location: 'Dbayeh',
    priceValue: 250,
    ratingValue: 4.4,
    reviewCount: 83,
  }),
  createEntertainment({
    id: 'dabke-group',
    title: 'DABKE GROUP',
    imageSrc: entertainmentAsset('dabkegroup', 'main.jpg'),
    imageAlt: 'Dabke dance group',
    galleryImages: entertainmentGallery('dabkegroup', 'Dabke Group', [
      'main.jpg',
      '1.jpg',
      '2.jpg',
      '3.jpeg',
    ]),
    description: 'Traditional dabke dancers for weddings, cultural events, and entrances.',
    detailsDescription: 'A lively dabke group with coordinated choreography, traditional energy, and audience engagement.',
    priceText: '350$/Show',
    vendorName: 'Levant Steps',
    vendorLocation: 'Saida',
    vendorLogoSrc: entertainmentAsset('dabkegroup', 'logo.png'),
    detailBadgeText: 'Traditional Dance',
    category: 'Dancing',
    location: 'Saida',
    priceValue: 350,
    ratingValue: 4.6,
    reviewCount: 69,
  }),
  createEntertainment({
    id: 'acoustic-duo',
    title: 'ACOUSTIC DUO',
    imageSrc: entertainmentAsset('accousticduo', 'main.avif'),
    imageAlt: 'Acoustic musicians',
    galleryImages: entertainmentGallery('accousticduo', 'Acoustic Duo', [
      'main.avif',
      '1.webp',
      '2.jpg',
      '3.webp',
    ]),
    description: 'Acoustic guitar and vocal duo for ceremonies, dinners, and cocktail hours.',
    detailsDescription: 'A warm acoustic duo with customizable setlists for wedding ceremonies, receptions, and intimate dinners.',
    priceText: '320$/Night',
    vendorName: 'Soft Strings',
    vendorLocation: 'Byblos',
    vendorLogoSrc: entertainmentAsset('accousticduo', 'logo.png'),
    detailBadgeText: 'Acoustic Music',
    category: 'Music',
    location: 'Byblos',
    priceValue: 320,
    ratingValue: 4.7,
    reviewCount: 58,
  }),
  createEntertainment({
    id: 'circus-performers',
    title: 'CIRCUS PERFORMERS',
    imageSrc: entertainmentAsset('circusperformers', 'main.avif'),
    imageAlt: 'Circus performers',
    galleryImages: entertainmentGallery('circusperformers', 'Circus Performers', [
      'main.avif',
      '1.jpg',
      '2.avif',
      '3.jpg',
    ]),
    description: 'Stilt walkers, jugglers, and roaming circus acts for lively events.',
    detailsDescription: 'A roaming circus entertainment package with visual performers, juggling, stilt walking, and guest interaction.',
    priceText: '420$/Day',
    vendorName: 'Carnival Crew',
    vendorLocation: 'Beirut',
    vendorLogoSrc: entertainmentAsset('circusperformers', 'logo.png'),
    detailBadgeText: 'Roaming Acts',
    category: 'Animation',
    location: 'Beirut',
    priceValue: 420,
    ratingValue: 4.5,
    reviewCount: 44,
  }),
  createEntertainment({
    id: 'karaoke-host',
    title: 'KARAOKE HOST',
    imageSrc: entertainmentAsset('karaokehost', 'main.avif'),
    imageAlt: 'Karaoke microphone',
    galleryImages: entertainmentGallery('karaokehost', 'Karaoke Host', [
      'main.avif',
      '1.jpeg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Hosted karaoke night with microphones, screen, and song library.',
    detailsDescription: 'A complete karaoke setup with a host, sound system, lyrics screen, microphones, and a wide song catalog.',
    priceText: '220$/Night',
    vendorName: 'Sing Along LB',
    vendorLocation: 'Hamra',
    vendorLogoSrc: entertainmentAsset('karaokehost', 'logo.png'),
    detailBadgeText: 'Karaoke',
    category: 'Interactive',
    location: 'Hamra',
    priceValue: 220,
    ratingValue: 4.2,
    reviewCount: 39,
  }),
  createEntertainment({
    id: 'led-dance-show',
    title: 'LED DANCE SHOW',
    imageSrc: entertainmentAsset('leddanceshow', 'main.jpg'),
    imageAlt: 'LED dance performance',
    galleryImages: entertainmentGallery('leddanceshow', 'LED Dance Show', [
      'main.jpg',
      '1.avif',
      '2.webp',
      '3.png',
    ]),
    description: 'High-impact LED dance performance for entrances and stage moments.',
    detailsDescription: 'A choreographed LED dance act with glowing costumes, upbeat music, and a visual stage presence.',
    priceText: '550$/Show',
    vendorName: 'Neon Motion',
    vendorLocation: 'Mar Mikhael',
    vendorLogoSrc: entertainmentAsset('leddanceshow', 'logo.png'),
    detailBadgeText: 'Stage Show',
    category: 'Dancing',
    location: 'Mar Mikhael',
    priceValue: 550,
    ratingValue: 4.6,
    reviewCount: 47,
    discountLabel: 'Visual act',
  }),
  createEntertainment({
    id: 'puppet-show',
    title: 'PUPPET SHOW',
    imageSrc: entertainmentAsset('puppetshow', 'main.webp'),
    imageAlt: 'Puppet show for kids',
    galleryImages: entertainmentGallery('puppetshow', 'Puppet Show', [
      'main.webp',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Story-driven puppet show for birthdays and school events.',
    detailsDescription: 'A child-friendly puppet show with stories, music, audience interaction, and a compact stage setup.',
    priceText: '150$/Show',
    vendorName: 'Story Box',
    vendorLocation: 'Jounieh',
    vendorLogoSrc: entertainmentAsset('puppetshow', 'logo.png'),
    detailBadgeText: 'Kids Show',
    category: 'Animation',
    location: 'Jounieh',
    priceValue: 150,
    ratingValue: 4.3,
    reviewCount: 35,
  }),
  createEntertainment({
    id: 'saxophonist',
    title: 'SAXOPHONIST',
    imageSrc: entertainmentAsset('saxophonist', 'main.jpg'),
    imageAlt: 'Saxophonist performing',
    galleryImages: entertainmentGallery('saxophonist', 'Saxophonist', [
      'main.jpg',
      '1.webp',
      '2.webp',
      '3.webp',
    ]),
    description: 'Solo saxophonist for cocktail hours, lounges, and wedding entrances.',
    detailsDescription: 'A solo saxophone performance with smooth, upbeat, or romantic sets tailored to the event mood.',
    priceText: '280$/Night',
    vendorName: 'Sax by Sam',
    vendorLocation: 'Achrafieh',
    vendorLogoSrc: entertainmentAsset('saxophonist', 'logo.png'),
    detailBadgeText: 'Solo Musician',
    category: 'Music',
    location: 'Achrafieh',
    priceValue: 280,
    ratingValue: 4.8,
    reviewCount: 73,
  }),
  createEntertainment({
    id: 'laser-show',
    title: 'LASER SHOW',
    imageSrc: entertainmentAsset('lasershow', 'main.webp'),
    imageAlt: 'Laser light show',
    galleryImages: entertainmentGallery('lasershow', 'Laser Show', [
      'main.webp',
      '1.jpg',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Laser light show synchronized with music for stages and dance floors.',
    detailsDescription: 'A programmed laser show with music synchronization, stage-safe setup, and high-impact lighting effects.',
    priceText: '850$/Show',
    vendorName: 'Beam Lab',
    vendorLocation: 'Beirut',
    vendorLogoSrc: entertainmentAsset('lasershow', 'logo.webp'),
    detailBadgeText: 'Light Show',
    category: 'Special Effects',
    location: 'Beirut',
    priceValue: 850,
    ratingValue: 4.6,
    reviewCount: 52,
    discountLabel: 'Premium',
  }),
]
