export const ENTERTAINMENT_ITEMS = [
  {
    id: 'face-painting-1',
    imageSrc:
      'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Face painting for kids',
    title: 'FACE PAINTING',
    description: 'Fun activity for kids of all ages.',
    detailsDescription:
      'A playful face painting experience with colorful designs for birthdays, school events, and family-friendly celebrations.',
    guestText: '',
    priceText: '30$/Day',
    vendorName: 'Fun Factory',
    vendorLocation: 'Beirut',
    ratingValue: 4.4,
    reviewCount: 76,
    detailBadgeText: 'Kids Activity',
    showPeopleSelector: false,
    datePlaceholder: 'Select Performance Date',
    timePlaceholder: 'Select Performance Time',
    actionButtonText: 'Add to Cart',
    category: 'Animation',
    location: 'Beirut',
    priceValue: 30,
  },
  {
    id: 'dj-rodge-1',
    imageSrc:
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'DJ performing at an event',
    title: 'DJ RODGE',
    description:
      'Experience the vibrant energy of DJ Rodge, delivering unforgettable house music sets that keep the crowd moving.',
    detailsDescription:
      'Experience the vibrant energy of DJ Rodge, delivering unforgettable house music sets that keep the crowd moving through weddings, private parties, and nightlife events.',
    guestText: '',
    priceText: '500$/Day',
    vendorName: 'DJ Rodge',
    vendorLocation: 'Jounieh',
    ratingValue: 4.5,
    reviewCount: 120,
    detailBadgeText: 'House Music',
    showPeopleSelector: false,
    datePlaceholder: 'Select Performance Date',
    timePlaceholder: 'Select Performance Time',
    actionButtonText: 'Add to Cart',
    category: 'Music',
    location: 'Jounieh',
    priceValue: 500,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/111111/ffffff.png&text=RODGE',
    vendorLogoAlt: 'Rodge logo',
  },
  {
    id: 'zaffe-1',
    imageSrc:
      'https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Traditional zaffe performers',
    title: 'ZAFFE',
    description: 'Traditional live entrance performance with dabke, drums, and festive energy.',
    detailsDescription:
      'A traditional zaffe performance with dancers, percussion, and celebratory movement to create a memorable entrance for weddings and major events.',
    guestText: '',
    priceText: '100$/Night',
    vendorName: 'Crystal Events',
    vendorLocation: 'Byblos',
    ratingValue: 4.6,
    reviewCount: 88,
    detailBadgeText: 'Live Performance',
    showPeopleSelector: false,
    datePlaceholder: 'Select Performance Date',
    timePlaceholder: 'Select Performance Time',
    actionButtonText: 'Add to Cart',
    category: 'Dancing',
    location: 'Byblos',
    priceValue: 100,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/f5f7fb/6f7b8a.png&text=Crystal+...',
    vendorLogoAlt: 'Crystal logo',
  },
  {
    id: 'face-painting-2',
    imageSrc:
      'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Face painting for kids',
    title: 'FACE PAINTING',
    description: 'Fun activity for kids of all ages.',
    detailsDescription:
      'A playful face painting experience with colorful designs for birthdays, school events, and family-friendly celebrations.',
    guestText: '',
    priceText: '30$/Day',
    vendorName: 'Fun Factory',
    vendorLocation: 'Tripoli',
    ratingValue: 4.4,
    reviewCount: 76,
    detailBadgeText: 'Kids Activity',
    showPeopleSelector: false,
    datePlaceholder: 'Select Performance Date',
    timePlaceholder: 'Select Performance Time',
    actionButtonText: 'Add to Cart',
    category: 'Animation',
    location: 'Tripoli',
    priceValue: 30,
  },
  {
    id: 'dj-rodge-2',
    imageSrc:
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'DJ performing at an event',
    title: 'DJ RODGE',
    description:
      'Experience the vibrant energy of DJ Rodge, delivering unforgettable house music sets that keep the crowd moving.',
    detailsDescription:
      'Experience the vibrant energy of DJ Rodge, delivering unforgettable house music sets that keep the crowd moving through weddings, private parties, and nightlife events.',
    guestText: '',
    priceText: '500$/Day',
    vendorName: 'DJ Rodge',
    vendorLocation: 'Beirut',
    ratingValue: 4.5,
    reviewCount: 120,
    detailBadgeText: 'House Music',
    showPeopleSelector: false,
    datePlaceholder: 'Select Performance Date',
    timePlaceholder: 'Select Performance Time',
    actionButtonText: 'Add to Cart',
    category: 'Music',
    location: 'Beirut',
    priceValue: 500,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/111111/ffffff.png&text=RODGE',
    vendorLogoAlt: 'Rodge logo',
  },
  {
    id: 'zaffe-2',
    imageSrc:
      'https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Traditional zaffe performers',
    title: 'ZAFFE',
    description: 'Traditional live entrance performance with dabke, drums, and festive energy.',
    detailsDescription:
      'A traditional zaffe performance with dancers, percussion, and celebratory movement to create a memorable entrance for weddings and major events.',
    guestText: '',
    priceText: '100$/Night',
    vendorName: 'Crystal Events',
    vendorLocation: 'Zahle',
    ratingValue: 4.6,
    reviewCount: 88,
    detailBadgeText: 'Live Performance',
    showPeopleSelector: false,
    datePlaceholder: 'Select Performance Date',
    timePlaceholder: 'Select Performance Time',
    actionButtonText: 'Add to Cart',
    category: 'Dancing',
    location: 'Zahle',
    priceValue: 100,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/f5f7fb/6f7b8a.png&text=Crystal+...',
    vendorLogoAlt: 'Crystal logo',
  },
]
