const menuLogo = (text, bg = 'ffffff', color = 'cc3b1e') =>
  `https://dummyimage.com/120x54/${bg}/${color}.png&text=${encodeURIComponent(text)}`

const menuAsset = (folder, fileName) => `/assets/menus/${folder}/${fileName}`

const menuGallery = (folder, menuName, fileNames) =>
  fileNames.map((fileName, index) => ({
    src: menuAsset(folder, fileName),
    alt:
      index === 0
        ? `${menuName} main image`
        : `${menuName} gallery image ${index}`,
  }))

const createMenu = ({
  id,
  title,
  imageSrc,
  imageAlt,
  galleryImages,
  description,
  detailsDescription,
  vendorName,
  vendorLocation,
  vendorLogoSrc,
  vendorLogoAlt,
  category,
  location,
  isVegan,
  minGuests,
  maxGuests,
  priceValue,
  ratingValue,
  reviewCount,
  discountLabel = '',
  logoText,
}) => ({
  id,
  imageSrc,
  imageAlt,
  title,
  description,
  detailsDescription,
  guestText: `Guests: ${minGuests} - ${maxGuests}`,
  priceText: `${priceValue}$/Person`,
  discountLabel,
  vendorName,
  vendorLocation,
  ratingValue,
  reviewCount,
  category,
  location,
  isVegan,
  minGuests,
  maxGuests,
  priceValue,
  vendorLogoSrc: vendorLogoSrc || menuLogo(logoText || vendorName),
  vendorLogoAlt: vendorLogoAlt || `${vendorName} logo`,
  galleryImages:
    Array.isArray(galleryImages) && galleryImages.length > 0
      ? galleryImages
      : [
          {
            src: imageSrc,
            alt: imageAlt,
          },
        ],
})

export const MENU_ITEMS = [
  createMenu({
    id: 'lebanese-grill',
    title: 'Lebanese Grill',
    imageSrc: menuAsset('lebanesegrill', 'main.avif'),
    imageAlt: 'Lebanese grill platter',
    galleryImages: menuGallery('lebanesegrill', 'Lebanese Grill', [
      'main.avif',
      '1.jpeg',
      '2.jpeg',
      '3.jpg',
    ]),
    description: 'A mix of meat, tawouk, and kafta with vegetable sides.',
    detailsDescription: 'A generous grill menu served with fries, onions, tomatoes, peppers, parsley, bread, and garlic dip.',
    vendorName: 'Lakkis',
    vendorLocation: 'Beirut',
    vendorLogoSrc: menuAsset('lebanesegrill', 'logo.png'),
    category: 'Lebanese',
    location: 'Beirut',
    isVegan: false,
    minGuests: 20,
    maxGuests: 100,
    priceValue: 15,
    ratingValue: 4.5,
    reviewCount: 120,
    discountLabel: '20% off for 50+ persons',
    logoText: 'Lakkis',
  }),
  createMenu({
    id: 'birthday-cake',
    title: 'Birthday Cake',
    imageSrc: menuAsset('birthdaycake', 'main.avif'),
    imageAlt: 'Chocolate birthday cake',
    galleryImages: menuGallery('birthdaycake', 'Birthday Cake', [
      'main.avif',
      '1.webp',
      '2.webp',
      '3.webp',
    ]),
    description: 'Cake with frosting of your choice and chocolate.',
    detailsDescription: 'Chocolate birthday cake with layered sponge, custom frosting, and decorative toppings for intimate celebrations.',
    vendorName: 'Al Safir',
    vendorLocation: 'Beirut',
    vendorLogoSrc: menuAsset('birthdaycake', 'logo.png'),
    category: 'Bakeries',
    location: 'Beirut',
    isVegan: true,
    minGuests: 2,
    maxGuests: 20,
    priceValue: 15,
    ratingValue: 4.7,
    reviewCount: 86,
    discountLabel: 'Vegan',
  }),
  createMenu({
    id: 'mixed-lunch',
    title: 'Mixed Lunch Menu',
    imageSrc: menuAsset('mixedlunchmenu', 'main.avif'),
    imageAlt: 'Mixed lunch table setup',
    galleryImages: menuGallery('mixedlunchmenu', 'Mixed Lunch Menu', [
      'main.avif',
      '1.webp',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Chicken with rice, salads, appetizers, and dessert.',
    detailsDescription: 'A complete lunch spread with chicken, rice, seasonal salads, appetizers, and dessert options for group events.',
    vendorName: 'Lakkis',
    vendorLocation: 'Beirut',
    vendorLogoSrc: menuAsset('mixedlunchmenu', 'logo.png'),
    category: 'Salads',
    location: 'Jounieh',
    isVegan: false,
    minGuests: 20,
    maxGuests: 100,
    priceValue: 15,
    ratingValue: 4.3,
    reviewCount: 95,
    logoText: 'Lakkis',
  }),
  createMenu({
    id: 'sushi-party',
    title: 'Sushi Party Box',
    imageSrc: menuAsset('sushipartybox', 'main.avif'),
    imageAlt: 'Assorted sushi platter',
    galleryImages: menuGallery('sushipartybox', 'Sushi Party Box', [
      'main.avif',
      '1.avif',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Assorted maki, nigiri, and rolls for cocktail-style events.',
    detailsDescription: 'A curated sushi selection with sauces, chopsticks, and cold-service presentation for private parties.',
    vendorName: 'Tokyo Table',
    vendorLocation: 'Jounieh',
    vendorLogoSrc: menuAsset('sushipartybox', 'logo.png'),
    category: 'Sushi',
    location: 'Jounieh',
    isVegan: false,
    minGuests: 10,
    maxGuests: 80,
    priceValue: 22,
    ratingValue: 4.6,
    reviewCount: 74,
  }),
  createMenu({
    id: 'vegan-mezze',
    title: 'Vegan Mezze',
    imageSrc: menuAsset('veganmezze', 'main.avif'),
    imageAlt: 'Vegan mezze spread',
    galleryImages: menuGallery('veganmezze', 'Vegan Mezze', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Plant-based Lebanese mezze with dips, salads, and warm bites.',
    detailsDescription: 'A vegan mezze menu including hummus, moutabbal, fattoush, stuffed vine leaves, falafel, and fresh bread.',
    vendorName: 'Green Saj',
    vendorLocation: 'Hamra',
    vendorLogoSrc: menuAsset('veganmezze', 'logo.png'),
    category: 'Lebanese',
    location: 'Hamra',
    isVegan: true,
    minGuests: 12,
    maxGuests: 90,
    priceValue: 13,
    ratingValue: 4.4,
    reviewCount: 58,
    discountLabel: 'Plant based',
  }),
  createMenu({
    id: 'italian-buffet',
    title: 'Italian Buffet',
    imageSrc: menuAsset('italianbuffet', 'main.avif'),
    imageAlt: 'Italian buffet table',
    galleryImages: menuGallery('italianbuffet', 'Italian Buffet', [
      'main.avif',
      '1.webp',
      '2.jpg',
      '3.webp',
    ]),
    description: 'Pasta, pizza slices, salads, and antipasti for casual gatherings.',
    detailsDescription: 'A warm Italian buffet with pasta trays, pizza selections, antipasti, green salads, and dessert bites.',
    vendorName: 'Casa Roma',
    vendorLocation: 'Achrafieh',
    vendorLogoSrc: menuAsset('italianbuffet', 'logo.png'),
    category: 'Italian',
    location: 'Achrafieh',
    isVegan: false,
    minGuests: 20,
    maxGuests: 150,
    priceValue: 18,
    ratingValue: 4.5,
    reviewCount: 101,
  }),
  createMenu({
    id: 'seafood-dinner',
    title: 'Seafood Dinner',
    imageSrc: menuAsset('seafooddinner', 'main.avif'),
    imageAlt: 'Seafood dinner platter',
    galleryImages: menuGallery('seafooddinner', 'Seafood Dinner', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Fresh fish, shrimp, calamari, sides, and coastal salads.',
    detailsDescription: 'A seafood dinner menu with grilled fish, shrimp, calamari, potatoes, dips, and seasonal coastal salads.',
    vendorName: 'Mina Seafood',
    vendorLocation: 'Tripoli',
    vendorLogoSrc: menuAsset('seafooddinner', 'logo.png'),
    category: 'Seafood',
    location: 'Tripoli',
    isVegan: false,
    minGuests: 15,
    maxGuests: 110,
    priceValue: 28,
    ratingValue: 4.6,
    reviewCount: 82,
  }),
  createMenu({
    id: 'brunch-box',
    title: 'Brunch Box',
    imageSrc: menuAsset('brunchbox', 'main.avif'),
    imageAlt: 'Brunch buffet setup',
    galleryImages: menuGallery('brunchbox', 'Brunch Box', [
      'main.avif',
      '1.jpg',
      '2.webp',
      '3.webp',
    ]),
    description: 'Mini croissants, eggs, cheese boards, fruit, and fresh juice.',
    detailsDescription: 'A bright brunch package with pastries, eggs, cheeses, fruit platters, juice, and light savory bites.',
    vendorName: 'Morning Table',
    vendorLocation: 'Byblos',
    vendorLogoSrc: menuAsset('brunchbox', 'logo.png'),
    category: 'Bakeries',
    location: 'Byblos',
    isVegan: false,
    minGuests: 8,
    maxGuests: 60,
    priceValue: 17,
    ratingValue: 4.4,
    reviewCount: 46,
  }),
  createMenu({
    id: 'bbq-station',
    title: 'BBQ Station',
    imageSrc: menuAsset('bbqstation', 'main.avif'),
    imageAlt: 'BBQ grill station',
    galleryImages: menuGallery('bbqstation', 'BBQ Station', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.jpeg',
    ]),
    description: 'Live BBQ station with burgers, skewers, grilled vegetables, and sides.',
    detailsDescription: 'A live BBQ setup with beef burgers, chicken skewers, grilled vegetables, corn, fries, sauces, and buns.',
    vendorName: 'Smoke Yard',
    vendorLocation: 'Keserwan',
    vendorLogoSrc: menuAsset('bbqstation', 'logo.png'),
    category: 'BBQ',
    location: 'Kaslik',
    isVegan: false,
    minGuests: 25,
    maxGuests: 180,
    priceValue: 20,
    ratingValue: 4.5,
    reviewCount: 91,
    discountLabel: 'Live station',
  }),
  createMenu({
    id: 'salad-bar',
    title: 'Fresh Salad Bar',
    imageSrc: menuAsset('freshsaladbar', 'main.avif'),
    imageAlt: 'Fresh salad bar',
    galleryImages: menuGallery('freshsaladbar', 'Fresh Salad Bar', [
      'main.avif',
      '1.jpg',
      '2.avif',
      '3.jpg',
    ]),
    description: 'Customizable salad bar with grains, greens, toppings, and dressings.',
    detailsDescription: 'A colorful salad bar with greens, roasted vegetables, grains, seeds, proteins, and house-made dressings.',
    vendorName: 'Fresh Fork',
    vendorLocation: 'Beirut',
    vendorLogoSrc: menuAsset('freshsaladbar', 'logo.png'),
    category: 'Salads',
    location: 'Beirut',
    isVegan: true,
    minGuests: 10,
    maxGuests: 120,
    priceValue: 12,
    ratingValue: 4.2,
    reviewCount: 55,
  }),
  createMenu({
    id: 'dessert-minis',
    title: 'Mini Dessert Table',
    imageSrc: menuAsset('minidesserttable', 'main.avif'),
    imageAlt: 'Mini dessert table',
    galleryImages: menuGallery('minidesserttable', 'Mini Dessert Table', [
      'main.avif',
      '1.webp',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Mini tarts, brownies, cookies, mousse cups, and seasonal sweets.',
    detailsDescription: 'A dessert display with bite-sized tarts, brownies, cookies, mousse cups, and seasonal sweet pieces.',
    vendorName: 'Sugar Studio',
    vendorLocation: 'Dbayeh',
    vendorLogoSrc: menuAsset('minidesserttable', 'logo.png'),
    category: 'Bakeries',
    location: 'Dbayeh',
    isVegan: false,
    minGuests: 15,
    maxGuests: 130,
    priceValue: 10,
    ratingValue: 4.7,
    reviewCount: 112,
    discountLabel: 'Best Seller',
  }),
  createMenu({
    id: 'breakfast-manakish',
    title: 'Manakish Breakfast',
    imageSrc: menuAsset('manakishbreakfast', 'main.webp'),
    imageAlt: 'Manakish breakfast spread',
    galleryImages: menuGallery('manakishbreakfast', 'Manakish Breakfast', [
      'main.webp',
      '1.jpg',
      '2.webp',
      '3.jpg',
    ]),
    description: 'Zaatar, cheese, lahm bi ajin, vegetables, olives, and tea.',
    detailsDescription: 'A traditional breakfast spread with assorted manakish, fresh vegetables, olives, labneh, and tea service.',
    vendorName: 'Saj House',
    vendorLocation: 'Saida',
    vendorLogoSrc: menuAsset('manakishbreakfast', 'logo.png'),
    category: 'Lebanese',
    location: 'Saida',
    isVegan: false,
    minGuests: 20,
    maxGuests: 160,
    priceValue: 9,
    ratingValue: 4.3,
    reviewCount: 67,
  }),
  createMenu({
    id: 'kids-party-menu',
    title: 'Kids Party Menu',
    imageSrc: menuAsset('kidspartymenu', 'main.jpg'),
    imageAlt: 'Kids party food table',
    galleryImages: menuGallery('kidspartymenu', 'Kids Party Menu', [
      'main.jpg',
      '1.webp',
      '2.gif',
      '3.jpg',
    ]),
    description: 'Mini sandwiches, nuggets, fries, cupcakes, and juice boxes.',
    detailsDescription: 'A kid-friendly party menu with mini sandwiches, chicken bites, fries, cupcakes, fruit skewers, and juices.',
    vendorName: 'Tiny Bites',
    vendorLocation: 'Beirut',
    vendorLogoSrc: menuAsset('kidspartymenu', 'logo.png'),
    category: 'Bakeries',
    location: 'Beirut',
    isVegan: false,
    minGuests: 10,
    maxGuests: 70,
    priceValue: 11,
    ratingValue: 4.4,
    reviewCount: 49,
  }),
  createMenu({
    id: 'taco-fiesta',
    title: 'Taco Fiesta',
    imageSrc: menuAsset('tacofiesta', 'main.avif'),
    imageAlt: 'Taco party spread',
    galleryImages: menuGallery('tacofiesta', 'Taco Fiesta', [
      'main.avif',
      '1.webp',
      '2.jpg',
      '3.jpg',
    ]),
    description: 'Build-your-own tacos with chicken, beef, beans, salsa, and guacamole.',
    detailsDescription: 'A taco station with tortillas, chicken, beef, beans, salsa, guacamole, corn, cheese, and fresh toppings.',
    vendorName: 'El Camino',
    vendorLocation: 'Mar Mikhael',
    vendorLogoSrc: menuAsset('tacofiesta', 'logo.png'),
    category: 'Mexican',
    location: 'Mar Mikhael',
    isVegan: false,
    minGuests: 20,
    maxGuests: 130,
    priceValue: 16,
    ratingValue: 4.5,
    reviewCount: 76,
  }),
  createMenu({
    id: 'formal-plated-dinner',
    title: 'Formal Plated Dinner',
    imageSrc: menuAsset('formalplateddinner', 'main.avif'),
    imageAlt: 'Formal plated dinner',
    galleryImages: menuGallery('formalplateddinner', 'Formal Plated Dinner', [
      'main.avif',
      '1.jpg',
      '2.jpg',
      '3.avif',
    ]),
    description: 'Three-course plated dinner with starter, main, dessert, and table service.',
    detailsDescription: 'A formal dining menu with a plated starter, main course choice, dessert, bread service, and serving staff.',
    vendorName: 'Cedar Catering',
    vendorLocation: 'Beirut',
    vendorLogoSrc: menuAsset('formalplateddinner', 'logo.png'),
    category: 'International',
    location: 'Downtown Beirut',
    isVegan: false,
    minGuests: 30,
    maxGuests: 220,
    priceValue: 35,
    ratingValue: 4.8,
    reviewCount: 134,
    discountLabel: 'Premium',
  }),
]
