const menuLogo = (text, bg = 'ffffff', color = 'cc3b1e') =>
  `https://dummyimage.com/120x54/${bg}/${color}.png&text=${encodeURIComponent(text)}`

const createMenu = ({
  id,
  title,
  imageSrc,
  imageAlt,
  description,
  detailsDescription,
  vendorName,
  vendorLocation,
  category,
  location,
  isVegan,
  minGuests,
  maxGuests,
  priceValue,
  ratingValue,
  reviewCount,
  discountLabel = '',
  logoText,
}) => ({
  id,
  imageSrc,
  imageAlt,
  title,
  description,
  detailsDescription,
  guestText: `Guests: ${minGuests} - ${maxGuests}`,
  priceText: `${priceValue}$/Person`,
  discountLabel,
  vendorName,
  vendorLocation,
  ratingValue,
  reviewCount,
  category,
  location,
  isVegan,
  minGuests,
  maxGuests,
  priceValue,
  vendorLogoSrc: menuLogo(logoText || vendorName),
  vendorLogoAlt: `${vendorName} logo`,
})

export const MENU_ITEMS = [
  createMenu({
    id: 'lebanese-grill',
    title: 'Lebanese Grill',
    imageSrc: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Lebanese grill platter',
    description: 'A mix of meat, tawouk, and kafta with vegetable sides.',
    detailsDescription: 'A generous grill menu served with fries, onions, tomatoes, peppers, parsley, bread, and garlic dip.',
    vendorName: "Pain d'Or",
    vendorLocation: 'Beirut',
    category: 'Lebanese',
    location: 'Beirut',
    isVegan: false,
    minGuests: 20,
    maxGuests: 100,
    priceValue: 15,
    ratingValue: 4.5,
    reviewCount: 120,
    discountLabel: '20% off for 50+ persons',
    logoText: "Pain d'Or",
  }),
  createMenu({
    id: 'birthday-cake',
    title: 'Birthday Cake',
    imageSrc: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Chocolate birthday cake',
    description: 'Cake with frosting of your choice and chocolate.',
    detailsDescription: 'Chocolate birthday cake with layered sponge, custom frosting, and decorative toppings for intimate celebrations.',
    vendorName: 'Al Safir',
    vendorLocation: 'Beirut',
    category: 'Bakeries',
    location: 'Beirut',
    isVegan: true,
    minGuests: 2,
    maxGuests: 20,
    priceValue: 15,
    ratingValue: 4.7,
    reviewCount: 86,
    discountLabel: 'Vegan',
  }),
  createMenu({
    id: 'mixed-lunch',
    title: 'Mixed Lunch Menu',
    imageSrc: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Mixed lunch table setup',
    description: 'Chicken with rice, salads, appetizers, and dessert.',
    detailsDescription: 'A complete lunch spread with chicken, rice, seasonal salads, appetizers, and dessert options for group events.',
    vendorName: "Pain d'Or",
    vendorLocation: 'Beirut',
    category: 'Salads',
    location: 'Jounieh',
    isVegan: false,
    minGuests: 20,
    maxGuests: 100,
    priceValue: 15,
    ratingValue: 4.3,
    reviewCount: 95,
    logoText: "Pain d'Or",
  }),
  createMenu({
    id: 'sushi-party',
    title: 'Sushi Party Box',
    imageSrc: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Assorted sushi platter',
    description: 'Assorted maki, nigiri, and rolls for cocktail-style events.',
    detailsDescription: 'A curated sushi selection with sauces, chopsticks, and cold-service presentation for private parties.',
    vendorName: 'Tokyo Table',
    vendorLocation: 'Jounieh',
    category: 'Sushi',
    location: 'Jounieh',
    isVegan: false,
    minGuests: 10,
    maxGuests: 80,
    priceValue: 22,
    ratingValue: 4.6,
    reviewCount: 74,
  }),
  createMenu({
    id: 'vegan-mezze',
    title: 'Vegan Mezze',
    imageSrc: 'https://images.unsplash.com/photo-1543352634-a1c51d9f1fa7?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Vegan mezze spread',
    description: 'Plant-based Lebanese mezze with dips, salads, and warm bites.',
    detailsDescription: 'A vegan mezze menu including hummus, moutabbal, fattoush, stuffed vine leaves, falafel, and fresh bread.',
    vendorName: 'Green Saj',
    vendorLocation: 'Hamra',
    category: 'Lebanese',
    location: 'Hamra',
    isVegan: true,
    minGuests: 12,
    maxGuests: 90,
    priceValue: 13,
    ratingValue: 4.4,
    reviewCount: 58,
    discountLabel: 'Plant based',
  }),
  createMenu({
    id: 'italian-buffet',
    title: 'Italian Buffet',
    imageSrc: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Italian buffet table',
    description: 'Pasta, pizza slices, salads, and antipasti for casual gatherings.',
    detailsDescription: 'A warm Italian buffet with pasta trays, pizza selections, antipasti, green salads, and dessert bites.',
    vendorName: 'Casa Roma',
    vendorLocation: 'Achrafieh',
    category: 'Italian',
    location: 'Achrafieh',
    isVegan: false,
    minGuests: 20,
    maxGuests: 150,
    priceValue: 18,
    ratingValue: 4.5,
    reviewCount: 101,
  }),
  createMenu({
    id: 'seafood-dinner',
    title: 'Seafood Dinner',
    imageSrc: 'https://images.unsplash.com/photo-1559737558-2f5a35f4523b?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Seafood dinner platter',
    description: 'Fresh fish, shrimp, calamari, sides, and coastal salads.',
    detailsDescription: 'A seafood dinner menu with grilled fish, shrimp, calamari, potatoes, dips, and seasonal coastal salads.',
    vendorName: 'Mina Seafood',
    vendorLocation: 'Tripoli',
    category: 'Seafood',
    location: 'Tripoli',
    isVegan: false,
    minGuests: 15,
    maxGuests: 110,
    priceValue: 28,
    ratingValue: 4.6,
    reviewCount: 82,
  }),
  createMenu({
    id: 'brunch-box',
    title: 'Brunch Box',
    imageSrc: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Brunch buffet setup',
    description: 'Mini croissants, eggs, cheese boards, fruit, and fresh juice.',
    detailsDescription: 'A bright brunch package with pastries, eggs, cheeses, fruit platters, juice, and light savory bites.',
    vendorName: 'Morning Table',
    vendorLocation: 'Byblos',
    category: 'Bakeries',
    location: 'Byblos',
    isVegan: false,
    minGuests: 8,
    maxGuests: 60,
    priceValue: 17,
    ratingValue: 4.4,
    reviewCount: 46,
  }),
  createMenu({
    id: 'bbq-station',
    title: 'BBQ Station',
    imageSrc: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'BBQ grill station',
    description: 'Live BBQ station with burgers, skewers, grilled vegetables, and sides.',
    detailsDescription: 'A live BBQ setup with beef burgers, chicken skewers, grilled vegetables, corn, fries, sauces, and buns.',
    vendorName: 'Smoke Yard',
    vendorLocation: 'Keserwan',
    category: 'BBQ',
    location: 'Kaslik',
    isVegan: false,
    minGuests: 25,
    maxGuests: 180,
    priceValue: 20,
    ratingValue: 4.5,
    reviewCount: 91,
    discountLabel: 'Live station',
  }),
  createMenu({
    id: 'salad-bar',
    title: 'Fresh Salad Bar',
    imageSrc: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Fresh salad bar',
    description: 'Customizable salad bar with grains, greens, toppings, and dressings.',
    detailsDescription: 'A colorful salad bar with greens, roasted vegetables, grains, seeds, proteins, and house-made dressings.',
    vendorName: 'Fresh Fork',
    vendorLocation: 'Beirut',
    category: 'Salads',
    location: 'Beirut',
    isVegan: true,
    minGuests: 10,
    maxGuests: 120,
    priceValue: 12,
    ratingValue: 4.2,
    reviewCount: 55,
  }),
  createMenu({
    id: 'dessert-minis',
    title: 'Mini Dessert Table',
    imageSrc: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Mini dessert table',
    description: 'Mini tarts, brownies, cookies, mousse cups, and seasonal sweets.',
    detailsDescription: 'A dessert display with bite-sized tarts, brownies, cookies, mousse cups, and seasonal sweet pieces.',
    vendorName: 'Sugar Studio',
    vendorLocation: 'Dbayeh',
    category: 'Bakeries',
    location: 'Dbayeh',
    isVegan: false,
    minGuests: 15,
    maxGuests: 130,
    priceValue: 10,
    ratingValue: 4.7,
    reviewCount: 112,
    discountLabel: 'Best Seller',
  }),
  createMenu({
    id: 'breakfast-manakish',
    title: 'Manakish Breakfast',
    imageSrc: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Manakish breakfast spread',
    description: 'Zaatar, cheese, lahm bi ajin, vegetables, olives, and tea.',
    detailsDescription: 'A traditional breakfast spread with assorted manakish, fresh vegetables, olives, labneh, and tea service.',
    vendorName: 'Saj House',
    vendorLocation: 'Saida',
    category: 'Lebanese',
    location: 'Saida',
    isVegan: false,
    minGuests: 20,
    maxGuests: 160,
    priceValue: 9,
    ratingValue: 4.3,
    reviewCount: 67,
  }),
  createMenu({
    id: 'kids-party-menu',
    title: 'Kids Party Menu',
    imageSrc: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Kids party food table',
    description: 'Mini sandwiches, nuggets, fries, cupcakes, and juice boxes.',
    detailsDescription: 'A kid-friendly party menu with mini sandwiches, chicken bites, fries, cupcakes, fruit skewers, and juices.',
    vendorName: 'Tiny Bites',
    vendorLocation: 'Beirut',
    category: 'Bakeries',
    location: 'Beirut',
    isVegan: false,
    minGuests: 10,
    maxGuests: 70,
    priceValue: 11,
    ratingValue: 4.4,
    reviewCount: 49,
  }),
  createMenu({
    id: 'taco-fiesta',
    title: 'Taco Fiesta',
    imageSrc: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Taco party spread',
    description: 'Build-your-own tacos with chicken, beef, beans, salsa, and guacamole.',
    detailsDescription: 'A taco station with tortillas, chicken, beef, beans, salsa, guacamole, corn, cheese, and fresh toppings.',
    vendorName: 'El Camino',
    vendorLocation: 'Mar Mikhael',
    category: 'Mexican',
    location: 'Mar Mikhael',
    isVegan: false,
    minGuests: 20,
    maxGuests: 130,
    priceValue: 16,
    ratingValue: 4.5,
    reviewCount: 76,
  }),
  createMenu({
    id: 'formal-plated-dinner',
    title: 'Formal Plated Dinner',
    imageSrc: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Formal plated dinner',
    description: 'Three-course plated dinner with starter, main, dessert, and table service.',
    detailsDescription: 'A formal dining menu with a plated starter, main course choice, dessert, bread service, and serving staff.',
    vendorName: 'Cedar Catering',
    vendorLocation: 'Beirut',
    category: 'International',
    location: 'Downtown Beirut',
    isVegan: false,
    minGuests: 30,
    maxGuests: 220,
    priceValue: 35,
    ratingValue: 4.8,
    reviewCount: 134,
    discountLabel: 'Premium',
  }),
]
