export const VENDOR_DIRECTORY = [
  {
    id: 'grand-hills-village',
    name: 'Grand Hills Village',
    logoText: 'GH',
    serviceType: 'Venues',
    location: 'Broumana',
    title: 'Grand Hills Village',
    description:
      'Experience the pinnacle of luxury in the heart of Broumana with breathtaking mountain views.',
    ctaLabel: 'View Items',
    imageSrc:
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1600&q=80',
    imageAlt: 'Elegant ballroom venue with chandeliers and floral centerpieces',
    badge: 'Featured Venue',
    featured: true,
  },
  {
    id: 'artisan-catering',
    name: 'Artisan Catering',
    logoText: 'AC',
    serviceType: 'Menus',
    location: 'Beirut',
    title: 'Artisan Catering',
    description: 'Curated menus for intimate gatherings and grand celebrations.',
    ctaLabel: 'View Items',
    imageSrc:
      'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Elegant catering dishes plated for an event',
  },
  {
    id: 'pain-dor',
    name: "Pain d'Or",
    logoText: 'PD',
    serviceType: 'Menus',
    location: 'Beirut',
    title: "Pain d'Or",
    description: 'Reliable catering for weddings, office events, and family celebrations.',
    ctaLabel: 'Explore Menus',
    imageSrc:
      'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Lebanese catering platter',
  },
  {
    id: 'abeille-dor',
    name: "Abeille d'Or",
    logoText: 'AD',
    serviceType: 'Menus',
    location: 'Jounieh',
    title: "Abeille d'Or",
    description: 'Premium pastry tables, desserts, and bespoke event sweets.',
    ctaLabel: 'Explore Menus',
    imageSrc:
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Premium dessert and cake vendor setup',
  },
  {
    id: 'party-corner',
    name: 'Party Corner',
    logoText: 'PC',
    serviceType: 'Decorations',
    location: 'Beirut',
    title: 'Party Corner',
    description: 'Playful styling, balloon concepts, and cheerful party installations.',
    ctaLabel: 'View Decor',
    imageSrc:
      'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Balloon decoration concept',
  },
  {
    id: 'glow-house',
    name: 'Glow House',
    logoText: 'GL',
    serviceType: 'Decorations',
    location: 'Jounieh',
    title: 'Glow House',
    description: 'Lighting-first setups that transform indoor and rooftop celebrations.',
    ctaLabel: 'View Decor',
    imageSrc:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event lights and glow decor',
  },
  {
    id: 'dj-rodge',
    name: 'DJ Rodge',
    logoText: 'DR',
    serviceType: 'Entertainment',
    location: 'Jounieh',
    title: 'DJ Rodge',
    description: 'High-energy music sets for nightlife events, weddings, and private parties.',
    ctaLabel: 'Book Talent',
    imageSrc:
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'DJ performance at night',
  },
  {
    id: 'caracalla-dance-theatre',
    name: 'Caracalla Dance Theatre',
    logoText: 'CRCL',
    serviceType: 'Entertainment',
    location: 'Beirut',
    title: 'Caracalla Dance Theatre',
    description:
      'The world-renowned dance company offering custom choreographed performances for grand-scale events.',
    ctaLabel: 'Book Talent',
    imageSrc:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Dance theatre performance on stage',
  },
  {
    id: 'royal-hotel-plans',
    name: 'Royal Hotel',
    logoText: 'RH',
    serviceType: 'Bundles',
    location: 'Beirut',
    title: 'Royal Hotel Plans',
    description: 'Ready-made celebration bundles combining venue, catering, decor, and entertainment.',
    ctaLabel: 'View Plans',
    imageSrc:
      'https://images.unsplash.com/photo-1464349153735-7db50ed83c84?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Celebration package setup with birthday concept',
  },
]
