export const VENUE_ITEMS = [
  {
    id: 'loft-batroun-1',
    imageSrc:
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Modern loft venue in Batroun',
    title: 'LOFT',
    description: 'A cozy private venue for intimate events with a modern indoor setup and overnight stay option.',
    detailsDescription:
      'A compact modern loft tailored for intimate celebrations, private dinners, and small overnight gatherings with a calm indoor atmosphere.',
    guestText: 'Guests: 1 - 5',
    priceText: '50$/Night',
    discountLabel: '30% off on Monday',
    vendorName: 'Batroun Loft',
    vendorLocation: 'Batroun',
    ratingValue: 4.6,
    reviewCount: 48,
    detailBadgeText: 'Indoor',
    supportingInfoText: 'Guests: 1 - 5',
    peopleLabel: 'Number of people',
    datePlaceholder: 'Select Reservation Date',
    timePlaceholder: 'Select Reservation Time',
    actionButtonText: 'Add to Cart',
    location: 'Batroun',
    placement: 'indoor',
    time: 'night',
    minGuests: 1,
    maxGuests: 5,
    priceValue: 50,
  },
  {
    id: 'showroom-beirut-1',
    imageSrc:
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event showroom in Beirut',
    title: 'SHOWROOM',
    description: 'Discover our exclusive showroom, where elegance and creativity come together in a refined setting.',
    detailsDescription:
      'Discover our exclusive showroom, where elegance and creativity come together in a refined setting. Visit to experience inspiring displays that blend luxury, style, and innovation in every detail.',
    guestText: 'Guests: 50 - 200',
    priceText: '800$/Night',
    discountLabel: 'Best Seller',
    vendorName: 'Phoenicia Hotel',
    vendorLocation: 'Beirut',
    ratingValue: 4.5,
    reviewCount: 263,
    detailBadgeText: 'Indoor',
    supportingInfoText: 'Guests: 50 - 200',
    peopleLabel: 'Number of people',
    datePlaceholder: 'Select Reservation Date',
    timePlaceholder: 'Select Reservation Time',
    actionButtonText: 'Add to Cart',
    location: 'Beirut',
    placement: 'indoor',
    time: 'night',
    minGuests: 50,
    maxGuests: 200,
    priceValue: 800,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/e8fbff/2b78cc.png&text=Beit+Al+M...',
    vendorLogoAlt: 'Venue partner logo',
  },
  {
    id: 'outdoor-jbeil-1',
    imageSrc:
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Outdoor venue in Jbeil',
    title: 'GARDEN VENUE',
    description: 'An open-air destination for large celebrations with scenic surroundings and flexible event layouts.',
    detailsDescription:
      'A spacious outdoor venue in Jbeil designed for weddings, daytime events, and large celebrations with panoramic views and flexible setup possibilities.',
    guestText: 'Guests: 100 - 500',
    priceText: '650$/Night',
    discountLabel: '5 dates left this year',
    vendorName: 'Albergo Gardens',
    vendorLocation: 'Jbeil',
    ratingValue: 4.7,
    reviewCount: 184,
    detailBadgeText: 'Outdoor',
    supportingInfoText: 'Guests: 100 - 500',
    peopleLabel: 'Number of people',
    datePlaceholder: 'Select Reservation Date',
    timePlaceholder: 'Select Reservation Time',
    actionButtonText: 'Add to Cart',
    location: 'Jbeil',
    placement: 'outdoor',
    time: 'day',
    minGuests: 100,
    maxGuests: 500,
    priceValue: 650,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/f9f6ef/6f5a38.png&text=Albergo',
    vendorLogoAlt: 'Albergo logo',
  },
  {
    id: 'loft-batroun-2',
    imageSrc:
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Modern loft venue in Batroun',
    title: 'LOFT',
    description: 'A cozy private venue for intimate events with a modern indoor setup and overnight stay option.',
    detailsDescription:
      'A compact modern loft tailored for intimate celebrations, private dinners, and small overnight gatherings with a calm indoor atmosphere.',
    guestText: 'Guests: 1 - 5',
    priceText: '50$/Night',
    discountLabel: '30% off on Monday',
    vendorName: 'Batroun Loft',
    vendorLocation: 'Batroun',
    ratingValue: 4.6,
    reviewCount: 48,
    detailBadgeText: 'Indoor',
    supportingInfoText: 'Guests: 1 - 5',
    peopleLabel: 'Number of people',
    datePlaceholder: 'Select Reservation Date',
    timePlaceholder: 'Select Reservation Time',
    actionButtonText: 'Add to Cart',
    location: 'Batroun',
    placement: 'indoor',
    time: 'night',
    minGuests: 1,
    maxGuests: 5,
    priceValue: 50,
  },
  {
    id: 'showroom-beirut-2',
    imageSrc:
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event showroom in Beirut',
    title: 'SHOWROOM',
    description: 'Discover our exclusive showroom, where elegance and creativity come together in a refined setting.',
    detailsDescription:
      'Discover our exclusive showroom, where elegance and creativity come together in a refined setting. Visit to experience inspiring displays that blend luxury, style, and innovation in every detail.',
    guestText: 'Guests: 50 - 200',
    priceText: '800$/Night',
    discountLabel: 'Best Seller',
    vendorName: 'Phoenicia Hotel',
    vendorLocation: 'Beirut',
    ratingValue: 4.5,
    reviewCount: 263,
    detailBadgeText: 'Indoor',
    supportingInfoText: 'Guests: 50 - 200',
    peopleLabel: 'Number of people',
    datePlaceholder: 'Select Reservation Date',
    timePlaceholder: 'Select Reservation Time',
    actionButtonText: 'Add to Cart',
    location: 'Beirut',
    placement: 'indoor',
    time: 'night',
    minGuests: 50,
    maxGuests: 200,
    priceValue: 800,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/e8fbff/2b78cc.png&text=Beit+Al+M...',
    vendorLogoAlt: 'Venue partner logo',
  },
  {
    id: 'outdoor-jbeil-2',
    imageSrc:
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Outdoor venue in Jbeil',
    title: 'GARDEN VENUE',
    description: 'An open-air destination for large celebrations with scenic surroundings and flexible event layouts.',
    detailsDescription:
      'A spacious outdoor venue in Jbeil designed for weddings, daytime events, and large celebrations with panoramic views and flexible setup possibilities.',
    guestText: 'Guests: 100 - 500',
    priceText: '650$/Night',
    discountLabel: '5 dates left this year',
    vendorName: 'Albergo Gardens',
    vendorLocation: 'Jbeil',
    ratingValue: 4.7,
    reviewCount: 184,
    detailBadgeText: 'Outdoor',
    supportingInfoText: 'Guests: 100 - 500',
    peopleLabel: 'Number of people',
    datePlaceholder: 'Select Reservation Date',
    timePlaceholder: 'Select Reservation Time',
    actionButtonText: 'Add to Cart',
    location: 'Jbeil',
    placement: 'outdoor',
    time: 'day',
    minGuests: 100,
    maxGuests: 500,
    priceValue: 650,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/f9f6ef/6f5a38.png&text=Albergo',
    vendorLogoAlt: 'Albergo logo',
  },
]
