const venueLogo = (text, bg = 'f9f6ef', color = '6f5a38') =>
  `https://dummyimage.com/120x54/${bg}/${color}.png&text=${encodeURIComponent(text)}`

const createVenue = ({
  id,
  title,
  location,
  vendorName,
  imageSrc,
  imageAlt,
  description,
  detailsDescription,
  placement,
  time,
  minGuests,
  maxGuests,
  priceValue,
  ratingValue,
  reviewCount,
  discountLabel = '',
  logoText,
}) => ({
  id,
  imageSrc,
  imageAlt,
  title,
  description,
  detailsDescription,
  guestText: `Guests: ${minGuests} - ${maxGuests}`,
  priceText: `${priceValue}$/Night`,
  discountLabel,
  vendorName,
  vendorLocation: location,
  ratingValue,
  reviewCount,
  detailBadgeText: placement === 'indoor' ? 'Indoor' : 'Outdoor',
  supportingInfoText: `Guests: ${minGuests} - ${maxGuests}`,
  peopleLabel: 'Number of people',
  datePlaceholder: 'Select Reservation Date',
  timePlaceholder: 'Select Reservation Time',
  actionButtonText: 'Add to Cart',
  location,
  placement,
  time,
  minGuests,
  maxGuests,
  priceValue,
  vendorLogoSrc: venueLogo(logoText || vendorName),
  vendorLogoAlt: `${vendorName} logo`,
})

export const VENUE_ITEMS = [
  createVenue({
    id: 'loft-batroun',
    title: 'LOFT',
    location: 'Batroun',
    vendorName: 'Batroun Loft',
    imageSrc: 'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Modern loft venue in Batroun',
    description: 'A cozy private venue for intimate events with a modern indoor setup and overnight stay option.',
    detailsDescription: 'A compact modern loft tailored for intimate celebrations, private dinners, and small overnight gatherings with a calm indoor atmosphere.',
    placement: 'indoor',
    time: 'night',
    minGuests: 1,
    maxGuests: 5,
    priceValue: 50,
    ratingValue: 4.6,
    reviewCount: 48,
    discountLabel: '30% off on Monday',
  }),
  createVenue({
    id: 'showroom-beirut',
    title: 'SHOWROOM',
    location: 'Beirut',
    vendorName: 'Phoenicia Hotel',
    imageSrc: 'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event showroom in Beirut',
    description: 'An elegant showroom for polished private events, launches, and refined social gatherings.',
    detailsDescription: 'A refined indoor showroom with flexible seating, polished lighting, and a central Beirut location for upscale gatherings.',
    placement: 'indoor',
    time: 'night',
    minGuests: 50,
    maxGuests: 200,
    priceValue: 800,
    ratingValue: 4.5,
    reviewCount: 263,
    discountLabel: 'Best Seller',
    logoText: 'Phoenicia',
  }),
  createVenue({
    id: 'garden-jbeil',
    title: 'GARDEN VENUE',
    location: 'Jbeil',
    vendorName: 'Albergo Gardens',
    imageSrc: 'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Outdoor garden venue in Jbeil',
    description: 'An open-air destination for large celebrations with scenic surroundings and flexible event layouts.',
    detailsDescription: 'A spacious outdoor venue in Jbeil designed for weddings, daytime events, and large celebrations with panoramic views.',
    placement: 'outdoor',
    time: 'day',
    minGuests: 100,
    maxGuests: 500,
    priceValue: 650,
    ratingValue: 4.7,
    reviewCount: 184,
    discountLabel: '5 dates left this year',
  }),
  createVenue({
    id: 'seaside-byblos',
    title: 'SEASIDE TERRACE',
    location: 'Byblos',
    vendorName: 'Byblos Bay Club',
    imageSrc: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Seaside terrace venue',
    description: 'A breezy coastal terrace for sunset receptions, engagement parties, and summer dinners.',
    detailsDescription: 'A sea-facing terrace with open views, cocktail space, and flexible table plans for warm outdoor celebrations.',
    placement: 'outdoor',
    time: 'night',
    minGuests: 40,
    maxGuests: 180,
    priceValue: 700,
    ratingValue: 4.8,
    reviewCount: 141,
    discountLabel: 'Sunset view',
  }),
  createVenue({
    id: 'mountain-faqra-lodge',
    title: 'MOUNTAIN LODGE',
    location: 'Faqra',
    vendorName: 'Faqra Peaks',
    imageSrc: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Mountain lodge venue',
    description: 'A warm mountain lodge for winter dinners, retreats, and intimate celebrations.',
    detailsDescription: 'A cozy lodge surrounded by mountain scenery with indoor dining, lounge corners, and overnight hosting options.',
    placement: 'indoor',
    time: 'night',
    minGuests: 15,
    maxGuests: 80,
    priceValue: 420,
    ratingValue: 4.4,
    reviewCount: 73,
  }),
  createVenue({
    id: 'heritage-tripoli-hall',
    title: 'HERITAGE HALL',
    location: 'Tripoli',
    vendorName: 'Mina Heritage House',
    imageSrc: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Historic hall venue',
    description: 'A character-rich hall for cultural events, dinners, and family celebrations.',
    detailsDescription: 'A heritage indoor venue with arched details, warm lighting, and a formal layout suited for memorable gatherings.',
    placement: 'indoor',
    time: 'day',
    minGuests: 30,
    maxGuests: 160,
    priceValue: 380,
    ratingValue: 4.3,
    reviewCount: 62,
  }),
  createVenue({
    id: 'rooftop-achrafieh',
    title: 'CITY ROOFTOP',
    location: 'Achrafieh',
    vendorName: 'Skyline Beirut',
    imageSrc: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'City rooftop party venue',
    description: 'A skyline rooftop for birthdays, corporate mixers, and evening receptions.',
    detailsDescription: 'An outdoor rooftop with city views, lounge seating, bar setup, and a night-focused event atmosphere.',
    placement: 'outdoor',
    time: 'night',
    minGuests: 35,
    maxGuests: 150,
    priceValue: 550,
    ratingValue: 4.6,
    reviewCount: 118,
    discountLabel: 'Weekday offer',
  }),
  createVenue({
    id: 'vineyard-zahle',
    title: 'VINEYARD ESTATE',
    location: 'Zahle',
    vendorName: 'Bekaa Vineyard Estate',
    imageSrc: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Vineyard event venue',
    description: 'A vineyard estate for outdoor lunches, weddings, and countryside celebrations.',
    detailsDescription: 'A scenic vineyard property with open lawns, tasting spaces, and wide table layouts for daytime events.',
    placement: 'outdoor',
    time: 'day',
    minGuests: 60,
    maxGuests: 300,
    priceValue: 620,
    ratingValue: 4.7,
    reviewCount: 97,
  }),
  createVenue({
    id: 'ballroom-verdun',
    title: 'GRAND BALLROOM',
    location: 'Verdun',
    vendorName: 'Verdun Palace',
    imageSrc: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Grand ballroom venue',
    description: 'A formal ballroom for weddings, gala dinners, and milestone celebrations.',
    detailsDescription: 'A large indoor ballroom with stage capacity, banquet seating, and premium service flow for high-guest events.',
    placement: 'indoor',
    time: 'night',
    minGuests: 120,
    maxGuests: 650,
    priceValue: 1200,
    ratingValue: 4.8,
    reviewCount: 231,
    discountLabel: 'Premium',
  }),
  createVenue({
    id: 'poolside-kaslik',
    title: 'POOLSIDE LOUNGE',
    location: 'Kaslik',
    vendorName: 'Kaslik Aqua Club',
    imageSrc: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Poolside event lounge',
    description: 'A relaxed poolside venue for summer parties, birthdays, and casual receptions.',
    detailsDescription: 'An outdoor poolside space with lounge seating, music setup, and flexible standing or seated arrangements.',
    placement: 'outdoor',
    time: 'day',
    minGuests: 25,
    maxGuests: 140,
    priceValue: 450,
    ratingValue: 4.2,
    reviewCount: 54,
  }),
  createVenue({
    id: 'studio-mar-mikhael',
    title: 'CREATIVE STUDIO',
    location: 'Mar Mikhael',
    vendorName: 'Studio M',
    imageSrc: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Creative studio event venue',
    description: 'A flexible studio for workshops, launches, photo events, and private dinners.',
    detailsDescription: 'A minimalist indoor studio with movable furniture, clean walls, and adaptable lighting for creative events.',
    placement: 'indoor',
    time: 'day',
    minGuests: 10,
    maxGuests: 70,
    priceValue: 250,
    ratingValue: 4.5,
    reviewCount: 39,
  }),
  createVenue({
    id: 'orchard-broumana',
    title: 'ORCHARD GARDEN',
    location: 'Broumana',
    vendorName: 'Broumana Orchard',
    imageSrc: 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Orchard garden venue',
    description: 'A garden venue surrounded by trees for brunches, showers, and family events.',
    detailsDescription: 'A peaceful outdoor orchard with shaded areas, long-table options, and a natural daytime setting.',
    placement: 'outdoor',
    time: 'day',
    minGuests: 20,
    maxGuests: 120,
    priceValue: 340,
    ratingValue: 4.4,
    reviewCount: 68,
  }),
  createVenue({
    id: 'industrial-quarantina',
    title: 'INDUSTRIAL LOFT',
    location: 'Quarantina',
    vendorName: 'Warehouse 12',
    imageSrc: 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Industrial loft venue',
    description: 'A raw industrial venue for concerts, product launches, and large standing events.',
    detailsDescription: 'A spacious indoor warehouse with high ceilings, stage-friendly layout, and adaptable production capacity.',
    placement: 'indoor',
    time: 'night',
    minGuests: 150,
    maxGuests: 900,
    priceValue: 980,
    ratingValue: 4.5,
    reviewCount: 89,
  }),
  createVenue({
    id: 'beach-resort-tyre',
    title: 'BEACH RESORT',
    location: 'Tyre',
    vendorName: 'Tyre Sands Resort',
    imageSrc: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Beach resort event venue',
    description: 'A beachfront resort for destination weddings, summer events, and coastal dinners.',
    detailsDescription: 'A beachside outdoor resort with sand-level setups, sunset ceremonies, and open-air dining options.',
    placement: 'outdoor',
    time: 'night',
    minGuests: 80,
    maxGuests: 350,
    priceValue: 900,
    ratingValue: 4.7,
    reviewCount: 126,
    discountLabel: 'Summer favorite',
  }),
  createVenue({
    id: 'conference-downtown',
    title: 'CONFERENCE SUITE',
    location: 'Downtown Beirut',
    vendorName: 'Cedar Business Center',
    imageSrc: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Conference event suite',
    description: 'A polished suite for business events, panels, seminars, and private meetings.',
    detailsDescription: 'A modern indoor conference venue with presentation support, breakout areas, and seated hospitality service.',
    placement: 'indoor',
    time: 'day',
    minGuests: 20,
    maxGuests: 120,
    priceValue: 300,
    ratingValue: 4.3,
    reviewCount: 77,
  }),
]
