export const VENUE_ITEMS = [
  {
    id: 'loft-batroun-1',
    imageSrc:
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Modern loft venue in Batroun',
    title: 'Loft in Batroun',
    description: '',
    guestText: 'Guests: 1 - 5',
    priceText: '50$/Night',
    discountLabel: '30% off on Monday',
    location: 'Batroun',
    placement: 'indoor',
    time: 'night',
    minGuests: 1,
    maxGuests: 5,
    priceValue: 50,
  },
  {
    id: 'showroom-beirut-1',
    imageSrc:
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event showroom in Beirut',
    title: 'Showroom in Beirut',
    description: '',
    guestText: 'Guests: 50 - 200',
    priceText: '800$/Night',
    location: 'Beirut',
    placement: 'indoor',
    time: 'night',
    minGuests: 50,
    maxGuests: 200,
    priceValue: 800,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/e8fbff/2b78cc.png&text=Beit+Al+M...',
    vendorLogoAlt: 'Venue partner logo',
  },
  {
    id: 'outdoor-jbeil-1',
    imageSrc:
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Outdoor venue in Jbeil',
    title: 'Outdoor Venue in Jbeil',
    description: '',
    guestText: 'Guests: 100 - 500',
    priceText: '650$/Night',
    discountLabel: '5 dates left this year',
    location: 'Jbeil',
    placement: 'outdoor',
    time: 'day',
    minGuests: 100,
    maxGuests: 500,
    priceValue: 650,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/f9f6ef/6f5a38.png&text=Albergo',
    vendorLogoAlt: 'Albergo logo',
  },
  {
    id: 'loft-batroun-2',
    imageSrc:
      'https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Modern loft venue in Batroun',
    title: 'Loft in Batroun',
    description: '',
    guestText: 'Guests: 1 - 5',
    priceText: '50$/Night',
    discountLabel: '30% off on Monday',
    location: 'Batroun',
    placement: 'indoor',
    time: 'night',
    minGuests: 1,
    maxGuests: 5,
    priceValue: 50,
  },
  {
    id: 'showroom-beirut-2',
    imageSrc:
      'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Event showroom in Beirut',
    title: 'Showroom in Beirut',
    description: '',
    guestText: 'Guests: 50 - 200',
    priceText: '800$/Night',
    location: 'Beirut',
    placement: 'indoor',
    time: 'night',
    minGuests: 50,
    maxGuests: 200,
    priceValue: 800,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/e8fbff/2b78cc.png&text=Beit+Al+M...',
    vendorLogoAlt: 'Venue partner logo',
  },
  {
    id: 'outdoor-jbeil-2',
    imageSrc:
      'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=80',
    imageAlt: 'Outdoor venue in Jbeil',
    title: 'Outdoor Venue in Jbeil',
    description: '',
    guestText: 'Guests: 100 - 500',
    priceText: '650$/Night',
    discountLabel: '5 dates left this year',
    location: 'Jbeil',
    placement: 'outdoor',
    time: 'day',
    minGuests: 100,
    maxGuests: 500,
    priceValue: 650,
    vendorLogoSrc:
      'https://dummyimage.com/120x54/f9f6ef/6f5a38.png&text=Albergo',
    vendorLogoAlt: 'Albergo logo',
  },
]
